{
 "title": "Certificates Expiration (X509 Certificate Exporter)",
 "description": "Unified dashboard for checking certificates expiration: Kubernetes Secrets, certificate files on nodes, or on any server.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "critical_threshold", "label": "Critical Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   { "name": "warning_threshold", "label": "Warning Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   {
    "name": "list_threshold",
    "label": "List expiring in less than (days)",
    "query": "1,7,15,30,60,90,180,365,730,1095,1460,1825,3650,7300"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(x509_cert_not_after)" }
   ]
  },
  {
   "title": "Expired",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((x509_cert_not_after - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Expiring within $critical_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((x509_cert_not_after - time()) / 86400) < bool $critical_threshold)"
    }
   ]
  },
  {
   "title": "Expiring within $warning_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((x509_cert_not_after - time()) / 86400) < bool $warning_threshold)"
    }
   ]
  },
  {
   "title": "Media",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(x509_cert_not_after{secret_name!=\"\"})",
     "legendFormat": "Kubernetes Secret"
    },
    {
     "expr": "count(x509_cert_not_after{filepath!=\"\",embedded_key!=\"\"})",
     "legendFormat": "Kubeconfig Embedded"
    },
    {
     "expr": "count(x509_cert_not_after{filepath!=\"\",embedded_key=\"\"})",
     "legendFormat": "Certificate File"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(x509_read_errors)" }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(x509_read_errors)" }
   ]
  },
  { "title": "Expiration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Kubernetes Secrets (time left < $list_threshold days)",
   "type": "table",
   "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort(((x509_cert_not_after{secret_name!=\"\"} - time()) / 86400) < $list_threshold)"
    }
   ]
  },
  {
   "title": "Host Files (time left < $list_threshold days)",
   "type": "table",
   "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sort(((x509_cert_not_after{filepath!=\"\"} - time()) / 86400) < $list_threshold)"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Top Issuers",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(count by (issuer_CN) (x509_cert_not_after)))"
    }
   ]
  },
  {
   "title": "Top Namespaces (Kubernetes Secrets)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(count by (secret_namespace) (x509_cert_not_after{secret_namespace!=\"\"})))"
    }
   ]
  },
  {
   "title": "Top Instances (Host Paths)",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(count by (instance) (x509_cert_not_after{filepath!=\"\"})))"
    }
   ]
  },
  {
   "title": "Kubernetes Secrets : Shortest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "bottomk(10, (x509_cert_not_after{secret_name!=\"\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "Host Paths : Shortest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "bottomk(10, (x509_cert_not_after{filepath!=\"\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "Kubernetes Secrets : Longest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "topk(10, (x509_cert_not_after{secret_name!=\"\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "Host Paths : Longest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk(10, (x509_cert_not_after{filepath!=\"\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Reporting Exporters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(x509_read_errors)", "legendFormat": "exporters" }
   ]
  },
  {
   "title": "Exporters with Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (x509_read_errors > bool 0)",
     "legendFormat": "exporters with errors"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(x509_read_errors[15m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Cumulative Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(x509_read_errors)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Top Exporters by Error Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "topk(10, rate(x509_read_errors[6h]))"
    }
   ]
  },
  {
   "title": "Top Exporters by Cumulative Errors",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "targets": [
    { "expr": "topk(10, x509_read_errors)" }
   ]
  }
 ]
}