#!/bin/bash
set -euo pipefail

NAMESPACE="apps"
RELEASE_NAME="bitwarden"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values-public.yaml \
  --values <(sops -d ../../secrets/bitwarden-values.yaml)
