---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
image:
  repository: vaultwarden/server
  tag: 1.37.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  loadBalancerIP: null

httpRoute:
  enabled: true
  path: /
  hosts:
    - bitwarden.shpaq.org
  parentRefs:
    - name: traefik-gateway
      namespace: kube-system
      kind: Gateway
      sectionName: websecure

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector:
  kubernetes.io/role: worker

tolerations: []
affinity: {}
podAnnotations: {}
deploymentAnnotations: {}
#    backup.velero.io/backup-volumes: bitwarden

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

persistence:
  enabled: false
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 2Gi

podDisruptionBudget: {}
#    minAvailable: 1
hpa:
  enabled: false
vpa:
  enabled: false
