#!/bin/bash

# Check if grafana repo is already added
if ! helm repo list | grep -q "grafana"; then
    echo "Adding grafana Helm repository..."
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
else
    echo "grafana repository already exists"
fi

# Update helm repositories
helm repo update

sops -d --output grafana-admin-creds.yaml ../../secrets/grafana-admin-creds.yaml
sops -d --output grafana-backup-secret.yaml ../../secrets/grafana-backup-secret.yaml

kubectl apply -f grafana-admin-creds.yaml
kubectl apply -f grafana-backup-secret.yaml
kubectl apply -f backup-cronjob.yaml

helm upgrade --install grafana grafana/grafana -n monitoring -f values.yaml --version 10.3.0

rm -rf grafana-admin-creds.yaml grafana-backup-secret.yaml