{
 "title": "Host Overview",
 "tags": [
  "custom",
  "k3s",
  "node-exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(node_boot_time_seconds, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Free Filesystem Space (Lowest)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node*\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"$node\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$node\"}[24h]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$node\"}[24h]))"
    }
   ]
  },
  {
   "title": "Ram Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Slab_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Slab_bytes{instance=~\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "RAM Used %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum by (instance) (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"})) / (sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node\"})) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$node\", mode!=\"idle\"}[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "cpu busy %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[1m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device=~\"/dev/.*\"} - node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device=~\"/dev/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space available, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(min by (mountpoint) (node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device=~\"/dev/.*\",}/node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device=~\"/dev/.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Use per Filesystem",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$node\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=~\"$node\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}
{
 "title": "K8s Cluster Metrics",
 "description": "Summary metrics about cluster health, deployments, statefulsets, nodes, pods, containers running on Kubernetes nodes.",
 "tags": [
  "k3s",
  "custom"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/\"}) - sum (node_filesystem_free_bytes{nodename=~\"$node\",mountpoint=\"/\"})) / sum (node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage (2m)",
   "type": "stat",
   "description": "Cluster CPU usage (2m)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "SUM(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "stat",
   "description": "Cluster Memory Usage",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "description": "Shows local mounts capacity in realtime",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/\"}) - sum(node_filesystem_free_bytes{nodename=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{nodename=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "description": "Cluster Pod capacity in real time",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"}) - sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "description": "Cluster CPU capacity in real time",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    },
    {
     "expr": "SUM(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "description": "Cluster Ram memory capacity in real time",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"}) - sum(container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Cluster NFS Capacity",
   "type": "graph",
   "description": "Shows NFS capacity in realtime",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"rpi-k3s-worker4\",mountpoint=\"/data\"} - node_filesystem_free_bytes{instance=\"rpi-k3s-worker4\",mountpoint=\"/data\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"rpi-k3s-worker4\",mountpoint=\"/data\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Cluster Network I\\O",
   "type": "graph",
   "description": "Network Activity by Namespaces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{}[2m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{}[2m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$namespace$\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Statefulsets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Statefulset - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ statefulset}}"
    }
   ]
  },
  {
   "title": "Statefulset Replicas",
   "type": "stat",
   "description": "Number replicas of Statefulset with state Available",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Statefulset Replicas - Ready",
   "type": "stat",
   "description": "Number replicas of Stateful with state Ready",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Available",
   "type": "stat",
   "description": "Number replicas of Deployment with state Available",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Total",
   "type": "stat",
   "description": "Total number replicas of Deployment",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})+sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "description": "Number replicas of Deployment with state Unavailable",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes cluster monitoring (via Prometheus)",
 "description": "Monitor a Kubernetes cluster using Prometheus TSDB.  Shows overall cluster CPU / Memory / Disk usage as well as individual pod statistics. ",
 "tags": [ "custom" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Up Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"kubelet\"}) BY (job)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds)"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  },
  { "title": "Alarms", "type": "alertlist", "gridPos": { "h": 9, "w": 5, "x": 12, "y": 17 } },
  {
   "title": "Cluster Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{device=~\"/dev/.*\"}) ) / sum(node_filesystem_size_bytes{device=~\"/dev/.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Up Nodes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(up{job=\"kubelet\"}) BY (job)"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (pod)(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_rss{name=~\".+\"}) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_transmit_bytes_total{pod=~\".+\"}[5m])) by (pod))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_network_receive_bytes_total{pod=~\".+\"}[5m])) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (kubernetes_pod_name) (rate (container_network_receive_bytes_total{name!=\"\", kubernetes_pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "Receive Traffic"
    },
    {
     "expr": "sort_desc(sum by (kubernetes_pod_name) (rate (container_network_transmit_bytes_total{name!=\"\", kubernetes_pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "Transmit Traffic"
    }
   ]
  }
 ]
}
{
 "title": "Node Exporter Server Metrics",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode=\"system\"}) or count(node_cpu{instance=~\"$node\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",instance=~'$node'}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"nice\",instance=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"iowait\",instance=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"steal\",instance=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"irq\",instance=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node'} or node_memory_Buffers{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node'} or node_memory_Cached{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'} or node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node'} or node_memory_Slab{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node'} or node_memory_SwapCached{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node'} or node_memory_PageTables{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'} or node_memory_VmallocUsed{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'}) or (node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node'} or node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'} or node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~'$node'} or node_memory_Active{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node'} or node_memory_Inactive{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{instance=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])*100 or irate(node_disk_io_time_ms{instance=~\"$node\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node'}[5m]) or irate(node_disk_reads_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node'}[5m]) or irate(node_disk_writes_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~'$node'}[5m]) or irate(node_disk_sectors_read{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~'$node'}[5m]) or irate(node_disk_sectors_written{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{instance=~\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m]) or irate(node_context_switches{instance=~\"$node\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node'}[5m])*8 or irate(node_network_receive_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node'}[5m])*8 or irate(node_network_transmit_bytes{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}
{
 "title": "Pi k3s Simple Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(node:node_num_cpu:sum)" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Node Load 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype='ext4'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "node_network_up{device='eth0'}", "legendFormat": "STATUS" }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_duration_seconds_sum[5m]))"
    }
   ]
  },
  {
   "title": "TCP Established Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transmit Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}
{
 "title": "Traefik",
 "description": "Traefik Dashboard",
 "tags": [ "traefik" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "kube-system" },
   { "name": "percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src='https://i.imgur.com/hUJPiQ9.png' height='140px'/>"
   }
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"$namespace\",condition=\"true\",pod=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Global latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=\"200\",method=\"GET\"}[5m])) by (le))",
     "legendFormat": "Latency over 1 min"
    }
   ]
  },
  {
   "title": "Per node latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, rate(traefik_entrypoint_request_duration_seconds_bucket{code=\"200\",method=\"GET\"}[5m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Frontends (entrypoints)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total requests over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[5m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.1\",code=\"200\"}[5m])) by (job) / sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  { "title": "Backends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_bucket{le=\"0.1\",code=\"200\"}[5m])) by (job) / sum(rate(traefik_backend_request_duration_seconds_count{code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  { "title": "HTTP Code stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Status code 2xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"2..\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Status code 5xx over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Backend total requests over 1min per backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[1m])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code!~\"2..|5..\"}[5m])) by (method, code)",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  { "title": "Pod Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Traefik max memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"traefik-.*\"})",
     "legendFormat": "Max memory used"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"traefik-.*\"})",
     "legendFormat": "Requested memory usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"traefik-.*\"})",
     "legendFormat": "Limit memory usage"
    }
   ]
  },
  {
   "title": "Traefik max CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"traefik-.*\"}[1m]))",
     "legendFormat": "Max cpu used"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"traefik-.*\"})",
     "legendFormat": "Requested cpu usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"traefik-.*\"})",
     "legendFormat": "Limit cpu usage"
    }
   ]
  }
 ]
}