#!/bin/bash

# Check if ingress-nginx repo is already added
if ! helm repo list | grep -q "ingress-nginx"; then
    echo "Adding ingress-nginx Helm repository..."
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
else
    echo "ingress-nginx repository already exists"
fi

# Update helm repositories
helm repo update

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace kube-system --values values.yaml
