#!/bin/bash
./decrypt

kubectl apply -f .
kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

#rm -rf 00-secret.yaml
rm -rf 00-auth.yaml
