{{- if .Values.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "shpaq-org.fullname" . }}
  labels:
    {{- include "shpaq-org.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    - {{ .Values.httpRoute.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: security-chain
      backendRefs:
        - name: {{ include "shpaq-org.fullname" . }}
          port: 80
{{- end }}
