#!/bin/bash
set -euo pipefail

NAMESPACE="monitoring"
RELEASE_NAME="openweather-exporter"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values-public.yaml \
  --values <(sops -d ../../secrets/openweather-values.yaml)
