#!/bin/bash
set -euo pipefail

NAMESPACE="monitoring"
RELEASE_NAME="prometheus"
CHART="prometheus-community/prometheus"
VERSION="29.13.0"

# Add helm repo
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 2>/dev/null || true
helm repo update

kubectl apply -f <(sops -d ../../secrets/prometheus-secret.yaml) -n "${NAMESPACE}"

helm upgrade --install "${RELEASE_NAME}" "${CHART}" \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml \
  --version "${VERSION}"
