#!/bin/bash
set -euo pipefail

NAMESPACE="apps"
RELEASE_NAME="influxdb"
CHART="influxdata/influxdb"
VERSION="4.12.5"

# Add helm repo
helm repo add influxdata https://helm.influxdata.com/ 2>/dev/null || true
helm repo update

kubectl apply -f <(sops -d ../../secrets/influxdb-auth.yaml) -n "${NAMESPACE}"

helm upgrade --install "${RELEASE_NAME}" "${CHART}" \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml \
  --version "${VERSION}"
