{
 "title": "K3S Cluster Overview",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "k3s",
  "custom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_node_created,node)"
   },
   {
    "name": "namespace",
    "query": "query_result(kube_namespace_labels)"
   },
   {
    "name": "container",
    "query": "kube_pod_container_info{namespace=\"$namespace\"}"
   },
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overall cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Burstable  Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BestEffort  Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReadOnly PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly != 0) "
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" }
   ]
  },
  {
   "title": "Cluster Node Readiness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Overall Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"})",
     "legendFormat": "Total memory used"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    },
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Node Load5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "graph",
   "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace)(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Node CPU usage[5m] ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "Overall CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
     "legendFormat": "Total Used CPU in cluster"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "Total CPU in cluster"
    }
   ]
  },
  { "title": "$node Node details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$node uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " (\n (sum(time() - node_boot_time_seconds + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})) \nand \nON() kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n)"
    }
   ]
  },
  {
   "title": "Node Type",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 39 },
   "targets": [
    {
     "expr": "(kube_node_role{node=\"$node\"})",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "node_memory_Unevictable_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node evictions",
   "type": "stat",
   "description": "Number of Node evictions that happened since current instance of NodeController started. Sampled every 60 seconds.\n",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_collector_evictions_number{pod=~\".*.$node.*\"})"
    },
    {
     "expr": "node_memory_Unevictable_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{instance=\"$node\",pod!=\"\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "besteffort pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",container=\"POD\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "burstable pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id=~\".*.burstable.*\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "guaranteed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id!~\".*.burstable.*\",id!~\".*.besteffort.*\",node=\"$node\"}))"
    }
   ]
  },
  {
   "title": "Time synced",
   "type": "stat",
   "description": "Is clock synchronized to a reliable server (1 = yes, 0 = no). Sampled every 60 seconds.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node readiness for  $node ",
   "type": "stat",
   "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node Memory/Disk/PID Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Pod Count on $node  by namespace ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",k3s_io_hostname=\"$node\"})",
     "legendFormat": "{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Pod Startup Latency ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",instance=\"$node\"}",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  },
  {
   "title": "Node $node load5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=\"$node\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Node $node CPU usage",
   "type": "graph",
   "description": "record: instance:node_cpu_utilisation:rate1m\nexpr: 1\n  - avg without(cpu, mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m]))",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum by (instance) (instance:node_cpu_utilisation:rate1m)) + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Total CPU limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{node=\"$node\"})",
     "legendFormat": "total limits"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Node $node memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total memory requests on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Total Memory limits on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{node=\"$node\"})",
     "legendFormat": "total liimits "
    },
    {
     "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "$node disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (nodename,device) (node_filesystem_avail_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}))",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "(sum by (nodename,device) (node_filesystem_size_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}))"
    }
   ]
  },
  {
   "title": "Top 5  CPU guzzling pods on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": " sort(topk(5, container_cpu_usage_seconds_total{image!=\"\",instance=\"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5  memory guzzling pods on $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",instance=\"$node\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{instance=\"$node\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NodeNumberConntrackEntriesUsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_nf_conntrack_entries * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})\n  / (node_nf_conntrack_entries_limit * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node Network Errors Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_errs_total[5m]) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "- increase(node_network_transmit_errs_total[5m]) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}"
    }
   ]
  },
  {
   "title": "Node network interface flaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(node_network_up{device!~\"veth.+\",job=\"node-exporter\"}[2m]) *  on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Namespace $namespace details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Namespace $namespace SLO over $duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Burstable  Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum\n  by( namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=\"\",namespace=\"$namespace\"}[5m]))\n  / sum by( namespace) (increase(container_cpu_cfs_periods_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Guaranteed  Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\",id!~\".*.burstable.*|.*.besteffort.*\",id!~\".*.scope\",pod!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BestEffort  Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$namespace namespace creation time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_namespace_created{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Readiness in $namespace namespace",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}::{{container}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubernetes-cadvisor\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": " CPU usage by pod in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubernetes-cadvisor\",namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total CPU requests in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Requests in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage  in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(namespace) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubernetes-cadvisor\",namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory  Usage in namespace $namespace by pods",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 6, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubernetes-cadvisor\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API server errors for namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(name) (increase(aggregator_unavailable_apiservice_count{namespace=\"$namespace\"}[5m])) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": " $namespace pods on $node",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "(count by (pod)((kube_pod_status_scheduled{condition=\"true\"}) + on(pod,namespace) group_left(node) kube_pod_info{node=\"$node\",namespace=\"$namespace\"})) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod $container state in $namespace namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{namespace=\"$namespace\",container=\"$container\"}) ",
     "legendFormat": "READY::{{pod}}::container $container"
    },
    {
     "expr": "(kube_pod_container_status_waiting{namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "WAITING::{{pod}}::container $container "
    },
    {
     "expr": "(kube_pod_container_status_terminated{namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "TERMINATED::{{pod}}::container $container"
    }
   ]
  },
  {
   "title": "PersistentVolumeVlaim status in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVCs available capacity in namespacee $namespace",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{kubernetes_namespace=\"$namespace\"})\n  / sum(kube_persistentvolume_capacity_bytes{kubernetes_namespace=\"$namespace\"})\n ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pods Running in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}"
    },
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "PVCs Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=\"$namespace\"} != 0) "
    }
   ]
  },
  {
   "title": "PVCs Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=\"$namespace\"} != 0)"
    }
   ]
  },
  {
   "title": "Resource Quota in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 112 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.memory.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.storage.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    }
   ]
  },
  {
   "title": "Ingress in $namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_ingress_path{namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "API server status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API server certificate expiration time remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_client_certificate_expiration_seconds_count{job=\"apiserver\"}\n  > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job=\"apiserver\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API server availability over 30d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1\n  - ((sum(increase(apiserver_request_duration_seconds_count{verb=~\"POST|PUT|PATCH|DELETE\"}[30d]))\n  - sum(increase(apiserver_request_duration_seconds_bucket{le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d])))\n  + (sum(increase(apiserver_request_duration_seconds_count{verb=~\"LIST|GET\"}[30d]))\n  - (sum(increase(apiserver_request_duration_seconds_bucket{le=\"0.1\",scope=\"resource\",verb=~\"LIST|GET\"}[30d]))\n  + sum(increase(apiserver_request_duration_seconds_bucket{le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[30d]))\n  + sum(increase(apiserver_request_duration_seconds_bucket{le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[30d]))))\n  + sum(code:apiserver_request_total:increase30d{code=~\"5..\"})) / sum(code:apiserver_request_total:increase30d)"
    }
   ]
  },
  {
   "title": "apiserver_request:burnrate$duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[$duration]))\n  - (sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=\"resource\",verb=~\"LIST|GET\"}[$duration]))\n  + sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[$duration]))\n  + sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[$duration]))))\n  + sum(rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[$duration])))\n  / sum(rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[$duration]))"
    }
   ]
  },
  {
   "title": "API server latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (verb)((cluster:apiserver_request_duration_seconds:mean5m{job=\"apiserver\"}\n  > on(verb) group_left() (avg by(verb) (cluster:apiserver_request_duration_seconds:mean5m{job=\"apiserver\"}\n  >= 0) + 2 * stddev by(verb) (cluster:apiserver_request_duration_seconds:mean5m{job=\"apiserver\"}\n  >= 0))) > on(verb) group_left() 1.2 * avg by(verb) (cluster:apiserver_request_duration_seconds:mean5m{job=\"apiserver\"}\n  >= 0) and on(verb, resource) cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{job=\"apiserver\",quantile=\"0.99\"})",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API server total requests code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API server total requests resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API server errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\"}[5m]))\n  / sum by(verb) (rate(apiserver_request_total{job=\"apiserver\"}[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API aggregator_unavailable_apiservice_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(name, namespace) (increase(aggregator_unavailable_apiservice_count[5m])) ",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "API server total requests verb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  }
 ]
}