{
 "title": "Memory namespace",
 "description": "Showing memory in namespace, showing memory in nodes, and showing memory all cluster pods",
 "tags": [
  "kubernetes",
  "namespace",
  "memory"
 ],
 "time": { "from": "now", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_labels)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory load of nodes",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Namespaces memory usage",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_usage_bytes/1048576)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage in namespace ",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod,namespace) (container_memory_working_set_bytes{namespace=\"$namespace\"})/1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All pod memory usage",
   "type": "bargauge",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod,namespace) (container_memory_working_set_bytes)/1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}