#!/bin/bash
./decrypt

echo 'Creating namespace'
kubectl create namespace monitoring

echo 'Installing prometheus and node_exporter'
kubectl apply -f prometheus

echo 'Installing grafana'
kubectl apply -f grafana

rm -rf prometheus/15-auth.yaml
