---
dotfiles_zshrc_src: zshrc-gentoo
dotfiles_nvim_init_src: init-gentoo.vim
dotfiles_zsh_plugins:
  - colorize.zsh
  - fzf-completion.zsh
  - fzf-key-bindings.zsh
  - fzf-tab.zsh
  - grc.zsh
  - l.plugin.zsh
  - ls-colors.zsh
