---

- name: Base system setup (k3s cluster)
  hosts: k3s_cluster
  become: true
  gather_facts: true

  vars_files:
    - ../vars.yml

  tasks:
    - name: System
      ansible.builtin.include_role:
        name: system
      tags: ['system']
    - name: Dotfiles
      ansible.builtin.include_role:
        name: dotfiles
      tags: ['dotfiles']

#    - name: Rebooting hosts
#      reboot:
#        msg: "Pis are being rebooted"
#        reboot_timeout: 60
#      ignore_errors: true
