---

- name: Pi-hole setup
  hosts: pihole
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - name: System
      ansible.builtin.include_role:
        name: system
      tags: ['system']
    - name: Dotfiles
      ansible.builtin.include_role:
        name: dotfiles
      tags: ['dotfiles']
    - name: Pi-hole
      ansible.builtin.include_role:
        name: pihole
      tags: ['pihole']
