---
- name: Create audit rules dir if it does not exist
  ansible.builtin.file:
    path: /etc/audit/rules.d
    state: directory
    mode: "0755"

- name: Auditd configuration
  ansible.builtin.copy:
    src: auditd/{{ item }}
    dest: "/etc/audit/rules.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - 90-shpaq.rules
    - 99-finalize.rules
