---
- name: Disable APT recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/02norecommends
    mode: "0644"
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ system_apt_install_packages }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: system_apt_install_common
  retries: 5
  until: system_apt_install_common is success
  when:
    - system_apt_install_packages is defined
    - system_apt_install_packages is iterable
    - system_apt_install_packages | length > 0

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Remove packages
  when:
    - system_apt_remove_packages is defined
    - system_apt_remove_packages is iterable
    - system_apt_remove_packages | length > 0
  block:
    - name: Check if snap is installed
      ansible.builtin.debug:
        msg: "snapd is installed"
      register: system_snapd_check
      when:
        - "'snapd' in system_apt_remove_packages"
        - "'snapd' in ansible_facts.packages"
    - name: Remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop:
        - lxd
        - core18
        - core20
        - snapd
      changed_when: true
      when:
        - "'snapd' in system_apt_remove_packages"
        - "'snapd' in ansible_facts.packages"
        - system_snapd_check.failed is defined
    - name: Remove packages
      ansible.builtin.apt:
        name: "{{ system_apt_remove_packages }}"
        state: absent
        autoremove: true
    - name: Remove files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ ansible_user }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
        - "/etc/cloud"
        - "/var/lib/cloud"
      when:
        - "'snapd' in system_apt_remove_packages"
        - "'cloud-init' in system_apt_remove_packages"
