#!/bin/bash
set -euo pipefail

NAMESPACE="apps"
RELEASE_NAME="version-checker"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values-public.yaml \
  --values <(sops -d ./values.enc.yaml)
