#!/bin/bash
set -euo pipefail

NAMESPACE="auth"
RELEASE_NAME="authelia"
CHART="authelia/authelia"
VERSION="0.11.6"

# Add helm repo
helm repo add authelia https://charts.authelia.com 2>/dev/null || true
helm repo update

#kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

helm upgrade --install "${RELEASE_NAME}" "${CHART}" \
  --create-namespace \
  --namespace "${NAMESPACE}" \
  --values values.yaml \
  --values <( sops -d ../../secrets/authelia-values.yaml ) \
  --version "${VERSION}"

kubectl apply -f <(sops -d ../../secrets/authelia-secrets.yaml) -n "${NAMESPACE}"

