{{- range .Values.namespaces }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-chain
  namespace: {{ . }}
spec:
  chain:
    middlewares:
      - name: redirect-https
        namespace: traefik
      - name: geoblock
        namespace: traefik
      - name: hsts
        namespace: traefik
      - name: compress
        namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: {{ . }}
spec:
  forwardAuth:
    address: "http://authelia.auth.svc.cluster.local/api/authz/forward-auth"
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
{{- end }}
