image:
  repository: nginx
  tag: "1.31.3"

resources:
  requests:
    cpu: 8m
    memory: 8Mi
  limits:
    cpu: 24m
    memory: 64Mi

nodeSelector:
  kubernetes.io/role: worker

hpa:
  cpu:
    enabled: true
    targetAverageUtilization: 80
    minReplicas: 1
    maxReplicas: 2
  memory:
    enabled: false
    targetAverageValue: 24Mi
    minReplicas: 1
    maxReplicas: 2

httpRoute:
  enabled: true
  host: shpaq.org
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      kind: Gateway
      sectionName: websecure
