#!/bin/bash
set -euo pipefail

NAMESPACE="monitoring"
RELEASE_NAME="unifipoller"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values-public.yaml \
  --values <(sops -d ../../secrets/unifipoller-values.yaml)
