#!/bin/bash

# Check if unpoller repo is already added
#if ! helm repo list | grep -q "unpoller"; then
#    echo "Adding unpoller Helm repository..."
#    helm repo add unpoller https://unpoller.github.io/helm-chart
#
#else
#    echo "unpoller repository already exists"
#fi

#helm repo update

helm upgrade \
    --install unifipoller \
    --namespace monitoring \
    --values values-public.yaml \
    --values <(sops -d ../../secrets/unifipoller-values.yaml) \
    .
