{
 "title": "Temperature",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Now",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average temp gen2",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(node_hwmon_temp_celsius{sensor=\"temp0\",job=\"gen2\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average temp k3s",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(node_hwmon_temp_celsius{sensor=\"temp0\",job=\"kubernetes-pods\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gentoo",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{sensor=\"temp0\",job=\"gen2\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "K3s",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{sensor=\"temp0\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}