#!/bin/bash

# Check if grafana repo is already added
if ! helm repo list | grep -q "grafana"; then
    echo "Adding grafana Helm repository..."
    helm repo add grafana https://grafana.github.io/helm-charts
else
    echo "grafana repository already exists"
fi

# Update helm repositories
helm repo update

# Install loki
helm upgrade --install loki --create-namespace --namespace logging grafana/loki -f loki-values.yaml

# Install promtail
helm upgrade --install promtail --namespace logging grafana/promtail -f promtail-values.yaml
