#!/bin/bash

#helm repo add kubernetes-event-exporter https://resmoio.github.io/kubernetes-event-exporter
##helm repo update
helm upgrade --install \
  event-exporter \
  -n monitoring \
  -f./values.yaml \
  .
