#!/bin/bash
set -euo pipefail

NAMESPACE="media"
RELEASE_NAME="booklore"

kubectl apply -f <(sops -d ../../secrets/booklore-db-secret.yaml) -n "${NAMESPACE}"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml
