# Default values for booklore.
---
mariadb:
  enabled: true
  # Run MariaDB inside the app pod (inline) instead of a separate StatefulSet
  inline: true
  port: 3306
  image:
    repository: lscr.io/linuxserver/mariadb
    tag: "11.4.12"
    pullPolicy: IfNotPresent
  auth:
    database: booklore
    username: booklore
    password: ""
    existingSecret: "booklore-db-secret"
  rootPassword: ""
  env:
    PUID: "1000"
    PGID: "1000"
    TZ: "Europe/Warsaw"
  persistence:
    config:
      enabled: true
      size: 1Gi
      existingClaim: "booklore-mariadb-config"

image:
  # repository: ghcr.io/booklore-app/booklore
  repository: szpaczyn/booklore
  pullPolicy: IfNotPresent
  tag: "v1.18.5"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations:
  override-url.version-checker.io/mariadb: "ghcr.io/linuxserver/mariadb"
podLabels: {}

podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - SETPCAP
      - NET_BIND_SERVICE
      # - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
  # readOnlyRootFilesystem: false
  # runAsNonRoot: true
  # runAsUser: 568


service:
  type: ClusterIP
  port: 6060
  targetPort: http

httpRoute:
  enabled: true
  hosts:
    - host: booklore.shpaq.org
      paths:
        - path: /
          pathType: PathPrefix
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      kind: Gateway
      sectionName: websecure

resources:
  limits:
    cpu: 1500m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http

persistence:
  dataVolume:
    enabled: true
    size: 2000Mi
    existingClaim: "booklore-data"
  booksVolume:
    enabled: true
    size: 10Gi
    existingClaim: "media"
    subPath: "library/books"

extraVolumes:
  - name: bookdrop
    hostPath:
      path: /data/media/downloads/transmission/complete
      type: Directory

extraVolumeMounts:
  - name: bookdrop
    mountPath: /bookdrop
    readOnly: false

nodeSelector:
  kubernetes.io/role: worker

tolerations: []

affinity: {}

mounterInitContainer:
  enabled: true
  image: busybox
  tag: 1.37
