#!/bin/bash

# Check if nextcloud repo is already added
if ! helm repo list | grep -q "nextcloud"; then
    echo "Adding nextcloud Helm repository..."
    helm repo add nextcloud https://nextcloud.github.io/helm/
else
    echo "nextcloud repository already exists"
fi

# Update helm repositories
helm repo update

# helm repo add nextcloud https://nextcloud.github.io/helm/
sops -d \
    --output secret.yaml \
    ../../secrets/nextcloud-secret.yaml

kubectl apply -f secret.yaml -n apps
kubectl apply -f local-storage.yaml -n apps
helm upgrade --install cloud nextcloud/nextcloud -n apps -f values.yaml

rm -rf secret.yaml
