---
# Default values for whoops.

replicaCount: 1

image:
  repository: szpaczyn/whoops
  pullPolicy: Always
  tag: 1.1.1

service:
  type: ClusterIP
  port: 5000

httpRoute:
  enabled: true
  host: whoops.shpaq.org
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      kind: Gateway
      sectionName: websecure
