---
# Default values for whoops.

replicaCount: 1

image:
  repository: szpaczyn/whoops
  pullPolicy: Always
  tag: 1.1.1

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 250m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 96Mi

httpRoute:
  enabled: true
  host: whoops.shpaq.org
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      kind: Gateway
      sectionName: websecure
