#!/bin/bash
sops -d --output media-secret.yaml ../../secrets/media-secret.yaml
sops -d --output media-exporter-secret.yaml ../../secrets/media-exporter-secret.yaml

helm upgrade --install media-stack --namespace media --values values.yaml .


rm -rf media-secret.yaml
rm -rf media-exporter-secret.yaml
