#!/bin/bash
set -euo pipefail

NAMESPACE="media"
RELEASE_NAME="media-stack"

kubectl apply -f <(sops -d ../../secrets/media-secret.yaml) -n "${NAMESPACE}"
kubectl apply -f <(sops -d ../../secrets/media-exporter-secret.yaml) -n "${NAMESPACE}"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml
