#!/bin/bash
sops -d \
    --output secret.yaml \
    ../../secrets/nextcloud-secret.yaml

kubectl apply -f secret.yaml -n apps
helm upgrade --install cloud nextcloud/nextcloud -n apps -f values.yaml

rm -rf secret.yaml
