#!/bin/bash
set -euo pipefail

NAMESPACE="apps"
RELEASE_NAME="cloud"
CHART="nextcloud/nextcloud"
VERSION="9.2.5"

# Add helm repo
helm repo add nextcloud https://nextcloud.github.io/helm/ 2>/dev/null || true
helm repo update

kubectl apply -f <(sops -d ./nextcloud-secret.yaml) -n "${NAMESPACE}"
kubectl apply -f local-storage.yaml -n "${NAMESPACE}"

helm upgrade --install "${RELEASE_NAME}" "${CHART}" \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml \
  --version "${VERSION}"
