configMap:
    password_policy:
        standard:
            enabled: ENC[AES256_GCM,data:lLfNQQ==,iv:WA8tX0Yl3YBCw2CYmP+MkVOAM/KRI8JsGsxcIylANMo=,tag:SH0QG12Tfg/Df6Yt6ZKMaA==,type:bool]
            min_length: ENC[AES256_GCM,data:6fU=,iv:TQVzji2H9yc+L38qr7rM3RlpGfhc4NaG366Xv1JoxQ8=,tag:N7//YVz+D6Nn2pC8FdlJ5w==,type:int]
            require_uppercase: ENC[AES256_GCM,data:pegqcQ==,iv:2Xk3st4qkcFw7Rqo0vjW0mR39r/sfhwjJ1ytFmgq/5s=,tag:iclkWU7uYUHa63DOFMyMdg==,type:bool]
            require_lowercase: ENC[AES256_GCM,data:9frppQ==,iv:1pyF4a/9SiV3x6XLr7PkZUr2AFPK9GmCYpnGhBCLuQA=,tag:sr58WeasKQ0G1KLH7Ge76A==,type:bool]
            require_number: ENC[AES256_GCM,data:t15lLw==,iv:x+f8FC2OMrUixb6J8T8PllbM664Uab34fMsFxi5Txls=,tag:qRrO77H6rhcT5gXAMpATpQ==,type:bool]
            require_special: ENC[AES256_GCM,data:d7lNFg==,iv:B+UURr5wZQ9j1cyXTOo5XBfQjMx2Gx9zmOrWQWaEOU0=,tag:SmAhLhaxPCe4PTnYeatkeA==,type:bool]
    session:
        name: ENC[AES256_GCM,data:aewLAmXeLIGSdhaBqP/HXw==,iv:H2MxPN4KSe8eEBghOZwHicOFcguqkXjeuRo1/ZTtcMY=,tag:cjh7It7mtIkZ83bDKB8zpA==,type:str]
        same_site: ENC[AES256_GCM,data:WenX,iv:F7IFtivKyrqMWB9DEOTsqKaswSfkjNMDgXmQ1QCB6N0=,tag:CicxQ136tOyAdkyJgRbbHg==,type:str]
        expiration: ENC[AES256_GCM,data:x4YeRjfp0PE=,iv:SoRpAy2bcinqtbOla8HWCr9HyDwb6xbRq0NXgFaMYP0=,tag:YqKyfYFf6vzfzTAdrxL/sQ==,type:str]
        inactivity: ENC[AES256_GCM,data:oenwy6EUAg7j,iv:Br6ejr6LWBjxO83FdDXTzr5GXMqjk606wZsiULnR9Bc=,tag:K1t9VBHNbnSr9KP9dXMO9Q==,type:str]
        remember_me: ENC[AES256_GCM,data:Adw38mNARg==,iv:/QJSqmBzlIpWXDrcKSPP6bu0plo246/YCT8YCwWHOZI=,tag:Zy9yVigK6hFvVFfLRHa1Eg==,type:str]
        cookies:
            - domain: ENC[AES256_GCM,data:5eXA1JVEKk4i,iv:WRR7pGpIJiaucXPjUsgEllhnX1oiMx/Hh1Z9vp6qLIM=,tag:z09dfnPmtDIMYjNr9EVNXw==,type:str]
              default_redirection_url: ENC[AES256_GCM,data:iPOhVSuN6tl/rdpIpykKcgk=,iv:EomvMBPfpVnNMo9nuCHDMbZjCNE46ZjHgu+k6nqzByQ=,tag:8Ybt8kA1izj+lNCjKtJ+wA==,type:str]
              subdomain: ENC[AES256_GCM,data:SK3+7A==,iv:7xAUckrDBHHGReMHmNVHp1FMd2gkfnS0+YjS547LZF4=,tag:LraibOB3RIpM4tQAHAm69g==,type:str]
    regulation:
        max_retries: ENC[AES256_GCM,data:FA==,iv:bLGL79uChunFE4jvLNg6WMKYTwJW5nafJi67SYcXd/U=,tag:9BDeYUrug32DdbqwRR09LQ==,type:int]
        find_time: ENC[AES256_GCM,data:f4lR0BmhlirX,iv:73bZSF93Cx635jr9LrSJQyniuxzVAdahdBwSWHQN+hc=,tag:ToKMhaUuP+SEMdPKxFf3kg==,type:str]
        ban_time: ENC[AES256_GCM,data:tDc5LHix9mlk,iv:EqtQUWQkzKEpczksmuhdiJuR4gyAb3i8NEJ46jcOCNI=,tag:nPokVAoDR8AVA50SG33ojA==,type:str]
    notifier:
        filesystem:
            enabled: ENC[AES256_GCM,data:pzzK5Q==,iv:70P0UKu9fmMrbucBxbi/ZgfUyigLzNHI6GcR+Qa8frs=,tag:y9zP6jAxDNf1guUR/jI3lg==,type:bool]
            filename: ENC[AES256_GCM,data:MKJcaKbbVwBatCDh3lU0G37ktLLpVbK4,iv:4z9l+9V5aCIDW0NfEH9p4xP/ppLDQzKHE9BLnOHLgL0=,tag:wtbb1lT62nAbGFLFFYm5RA==,type:str]
    totp:
        issuer: ENC[AES256_GCM,data:0m+BV3fQTsou,iv:+4Mpr3XoorgOSmpDKjMQFzX1rrzfYbhNwAIsS8X0HiI=,tag:PH+ip1aKhXuP8KhepRK43g==,type:str]
    webauthn:
        disable: ENC[AES256_GCM,data:UqQ+ZZc=,iv:r/sqdqCSLk/dUJELJD9EBfyNFEZENHqxiQonizn14dA=,tag:S9cr5eaVd7wKqkRfJJplHw==,type:bool]
        display_name: ENC[AES256_GCM,data:sXCxeZb1h+xK,iv:fDBe6biW4eoTB23DK9uzkccf7TPpl+AbYinCnz5SN+0=,tag:wNtLIomQ64RXpC59tH72HQ==,type:str]
        enable_passkey_login: ENC[AES256_GCM,data:hOb1Xg==,iv:0wzsZQZOEkUFbFtwixEeA8ac+yS9vcgZjHUtBnqe5xE=,tag:IhKEWY+pMHiEW3goQSxdBA==,type:bool]
    access_control:
        default_policy: ENC[AES256_GCM,data:bdh1bw==,iv:C4jHhRHd1PssD3z1UopQLJmN8O6JPlK8rt0rZAq7Kaw=,tag:Jhplx5fawain9pbrU/GWSw==,type:str]
        rules:
            - domain: ENC[AES256_GCM,data:R2eO5BNvYaZZi32Sd6E=,iv:Jhoi2tE0iIeIMi7Xpdq9D3eqodZhx/SO0Nc4Beb196k=,tag:gKRM4CYLo5zWviW25c9dRw==,type:str]
              policy: ENC[AES256_GCM,data:77ovQEq0,iv:6OMIGixlITj99FFgyjGEe+HFj+EixwL+nyQhlNuzSJI=,tag:t25Fksqx5B/HP+P/Qufs+g==,type:str]
            - domain:
                - ENC[AES256_GCM,data:9YN10xZ2ARJC+d5lSwAg,iv:VDhxJNRjHFjEpnwV+xUliil67kJM/Jr1YDWOUlrEVlo=,tag:RFIB5RkDa9PdX1gD4Yf4XA==,type:str]
                - ENC[AES256_GCM,data:GV4LR4c48BusKjdW55udGbQ=,iv:6zCY68CoMeuQ7336sSTTppIT3oXY7Iwxm82fvgOiG9w=,tag:Rdj+VLu2QYRZwR4IHVHBdg==,type:str]
                - ENC[AES256_GCM,data:2KbIEHmGCBShlohHBf6S1w==,iv:eqibRaLZEC92C3c90EQTLXkN2+AX+0t8w5lFivtUD98=,tag:4PwGiSi6CcAHHz7kA2G9og==,type:str]
                - ENC[AES256_GCM,data:AAvT7OV2tsgWxRInyV4MVHq5,iv:OOGLtXQFobsKra6qqPU9alalIlRvlvz3SThu1MGXqPw=,tag:XRb4HJnQyGQLSSzbNFlvGQ==,type:str]
                - ENC[AES256_GCM,data:WsDG9PrPGk5lNGUaIPG++XngDfA=,iv:vY32tFXAUM3SAq66cd0FDeir3vsgAhoOU+KsvjtyrQc=,tag:aMqjKkqGB/BVfVOOHhKVRw==,type:str]
              policy: ENC[AES256_GCM,data:77ovQEq0,iv:6OMIGixlITj99FFgyjGEe+HFj+EixwL+nyQhlNuzSJI=,tag:t25Fksqx5B/HP+P/Qufs+g==,type:str]
              networks:
                - ENC[AES256_GCM,data:FcZQqF4l9lgfcw==,iv:Hn/5MoHV9GeqDu8eY6g909v0yw3Xv35DQouqCanWa7A=,tag:ypX1jtkDSbwoGXBf88ztDQ==,type:str]
            - domain:
                - ENC[AES256_GCM,data:9YN10xZ2ARJC+d5lSwAg,iv:VDhxJNRjHFjEpnwV+xUliil67kJM/Jr1YDWOUlrEVlo=,tag:RFIB5RkDa9PdX1gD4Yf4XA==,type:str]
                - ENC[AES256_GCM,data:GV4LR4c48BusKjdW55udGbQ=,iv:6zCY68CoMeuQ7336sSTTppIT3oXY7Iwxm82fvgOiG9w=,tag:Rdj+VLu2QYRZwR4IHVHBdg==,type:str]
                - ENC[AES256_GCM,data:2KbIEHmGCBShlohHBf6S1w==,iv:eqibRaLZEC92C3c90EQTLXkN2+AX+0t8w5lFivtUD98=,tag:4PwGiSi6CcAHHz7kA2G9og==,type:str]
                - ENC[AES256_GCM,data:AAvT7OV2tsgWxRInyV4MVHq5,iv:OOGLtXQFobsKra6qqPU9alalIlRvlvz3SThu1MGXqPw=,tag:XRb4HJnQyGQLSSzbNFlvGQ==,type:str]
                - ENC[AES256_GCM,data:WsDG9PrPGk5lNGUaIPG++XngDfA=,iv:vY32tFXAUM3SAq66cd0FDeir3vsgAhoOU+KsvjtyrQc=,tag:aMqjKkqGB/BVfVOOHhKVRw==,type:str]
              policy: ENC[AES256_GCM,data:JE38xqxptJGeVQ==,iv:7QjtYScyiLsyXhpFnDBzA9uz86wyvPxEVsqayl87Yfw=,tag:gmaUYsSde1ZzPiCAx6DLsw==,type:str]
sops:
    lastmodified: "2026-08-22T15:20:13Z"
    mac: ENC[AES256_GCM,data:jyp2j8f1/YVkryGgY7su+p9fr7dXaLhfWAQHNk73OgBWOyLTPV90IkjyzBncrAfNwpXZTEVPNN7CX83VIkFRC4VJs6IF9qcLJNEd3zYDwOIaZS2t/Hpbq0c6yX9lSnomnLVFLL07yuAdYIs1jp8BGAxEu7/41pMe1ZzpebbiINk=,iv:9tZB9JDjopBJe163UmAYM9vX1VM63SEm62DZBTtQCb0=,tag:rsAHHEVKGxHV5WRD/QpuWw==,type:str]
    pgp:
        - created_at: "2026-08-17T12:26:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+JYfr+yUt9a7DB4p1TYV3j1TdjwHLsafvlPW2I1kj040U
            GEAnXJ5L9RnP8D/fwd+aFT0OLqBpqw2dlguSIKxywR3n/ZmuVfEwsNyP/BPLpbDG
            frWUzUt1irUlW81YmoawFbFWR3w8x/LQygZSetC6qraf8tJxxMKnL4XBA1NpTDTA
            GrmRooOAZ2Nkj+nf+e9lpjEnTDq79P6tb98ByZTG7VFldO7GWUC0Uwei89y/LhXz
            fYcvOEHY2dmDa6NWx52YrnTBjtCbOFgNEhF/4FvVHkwjLrmQN7MuQ/C8V5c+Jr/t
            wb96bUalAk1qIr2eH/gm3ghkgSDzMbcYKqx1zhuV/olCXWlD84aIDoR0PvHE5zuS
            L97N0IZulgtowgDE0GgPZy1XL8MPT5DjSok3DIMyTBk7zOSfhcktgbbmxdWG8HsR
            6n5si1+rpoTzTRCZYmGTZFZXixhWhRpMUqVLrXn0XC8Lice/ESuyCP6Ak7B8OcGQ
            jv/aQYHdtgZsinfWaGLka3Z/hfRXv/pmYBmI2qAEaFi5LjuPKWeaC3UfbqHlvwOl
            afFTXTU6vCls2h/f5FDtkylKc//fcl2yoMfhK83tf9auxVHn2CDngO7DQZAOA8DT
            MBSKgkWQABOgDoC8tCs1LoKpaV/ms/oUpGH6UdCj3/TJDVj7golnZ31PRUxUksfS
            XgFpOLL8sY5wOR1j1phVBj8KkP42QnmNyBPNL2BfR3JQoN2vbPSzvrrdTt0WHoDQ
            3Vc9fhccU8HjgD7W2WHQdhE2OIw1wKebWVLMDXkdA/sCUQ4WtXEHlpQkAF3s40A=
            =2zCG
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
