#ENC[AES256_GCM,data:oUSag3Z8zPT485TgeJ52/YSIhkElX2zjYZ6IQPRfTIf6gxSw+jk4nrmE4DKT+cx6FLfwAXCQ9W2AAk3u072a98aI,iv:jM7PulTs8ZdIn+r76nAFsXhb921kRtVig2IP7v23jGg=,tag:sZNvEQh2hV9+OhjL1fyXow==,type:comment]
#ENC[AES256_GCM,data:yf+nFwAB3ND+bFNbtnr3GDxjC+T8vvzZ8nLJErKN98Jhxi2EKLsqGZhvSqnl9u7qpteHVneDtE6taVJ4EujapAGJQnH/Uodrc2OjDVMz0FK7,iv:Zioa9mG4J3gjuBZFjqg7IIoVC2wbVfa6GNNjNcPDXhs=,tag:zZ1yY++4lqKkKU/5c+KSHw==,type:comment]
#ENC[AES256_GCM,data:yKxWKiaizXysUkoewRF7Lyi+DE5GFWD1UFHe+je9gh2ANPitizje2fuly3Lsfh7upUwTsb6oWMhU1XA1lTlAxp8grNViCg==,iv:U+qJqVTl9fJkCn3irn/nRwVuImhO7JmD52imABgVFrY=,tag:y19x7tO38s2HHucOAqsApg==,type:comment]
#
#ENC[AES256_GCM,data:qisb7MOhNgOyzEelqaH09IYmAi4T/ZQxWcMXJdjKl9Cpf3Nzi7TGTJsbFxnrEbhfju63KuQaAzmhrHYDs+TZpys=,iv:xJ84rn7JHop2Zf/S3m2V41cL3lGu+l4U+kPuawAwXD8=,tag:bLM3xqvrGy9Irm0Y7NTdGQ==,type:comment]
#ENC[AES256_GCM,data:De0JUdHnZ0AAqb2cyfqXRwt847pj68Ig7w8KksC7dKpwDyxXd1PH,iv:O+Uqb1qTjNJFIJPlyVMpUd6+0snncVwjENZe2L5uYsM=,tag:lolRmnJQbxFvqZY9uFTQKQ==,type:comment]
#ENC[AES256_GCM,data:pdrhU06pYH+nZ8s9A7SzjXT/6Y44MqwiwsTQi9IWUhQ0Vf3kLFl54152mLElbr1MZNXv3tABxLRJ9ta6cane/muK0LR7KmHH5+w=,iv:2HqeVZk9M76jSLm+GCKN8CtZ5UTbYt1HMjCYnryLkIU=,tag:kcKJBIB7hXrzuAs7P3jqGw==,type:comment]
#
#ENC[AES256_GCM,data:kz+4NOiJF+a8V6voLrMojXYu4RK1Sonkoy0lEYZKrhdjyiOcXT1UfTAKNTc=,iv:MCSTQrDaDilq0jlvOPhYpXerN9hw9fg9A0kWaSv1GQU=,tag:OzdgXXQV6YBkbs5Fj+oQ/w==,type:comment]
#ENC[AES256_GCM,data:OPihMGqFhEZPzmxn6tvBUznUfXlKAtD6gfQvy5ZAKtTZ1/D8vOb7H5o+CRWR,iv:X/jYEesaKHgSGhMcmaBI6KBqWuyO5Co495e9gYvyEi0=,tag:21pwvMp40O5BxA3xcEhAOg==,type:comment]
#ENC[AES256_GCM,data:+aKkCZv2rWgRGZOrK5YirJL00MiLtGUJYndWM9p7XwbuzpaMPeQB3tvJFFneBzF2hyw/P00cWT/UiEV4RendzATmOExuXuYOeVM6TO1x,iv:PsXGZF40hNPCvmcEqX7xNiquWdHys/yQAB10nISoFI0=,tag:TixJSUTY6LBTWDNp4v7XpA==,type:comment]
apiVersion: ENC[AES256_GCM,data:y64=,iv:URB3vTMVbXnUu4a1tWC/x8TeyeAfTVurc2DGe9DbfOQ=,tag:VhmHQxkZsjbphDE3Xcv09A==,type:str]
kind: ENC[AES256_GCM,data:+koOI03R,iv:aRR7qaPpTEKd4mk+EDND+FTc5xUOeIqAlWV5LnF71RY=,tag:3oKeDzDwXxfc+BasCwm9uQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sCwTCwxFoHtxonueng==,iv:6mseGFmbwCstHLAKY4BqQHLuf44k6FUiQSxhxkFjsQI=,tag:G0jBOTsvAcAxfLNst3h+mA==,type:str]
    namespace: ENC[AES256_GCM,data:ai62jEacDg==,iv:Wwzw8Mk+TUaqqm/A/FAeUfjtdVycw+KZKVGVht4fAuw=,tag:sG4Kc96jkm7Ag7Kv14IGnA==,type:str]
type: ENC[AES256_GCM,data:jMk1Hc5P,iv:HXCEFkiaCUMxr7BF2dd0G1maY7wN+5AlENo6jpyVDtg=,tag:X57/RKywtaETHVupTtHwNQ==,type:str]
stringData:
    account_id: ENC[AES256_GCM,data:rsx0pTnvIg==,iv:Fe3xlNM67w6i5uN2UuEWaWUIPqc+8eJ2WY5r8t9C+oM=,tag:qxNA9FyWicTZN2Yz7vjTIw==,type:str]
    license_key: ENC[AES256_GCM,data:2qHHM2QAWoTFJWsioDKVXUzdVGwxNWiGatZG2MPAm/ezVmh2WUA54Q==,iv:M9lY4KLkjtwewQ6V0XLRV3COCZnoz9S8dYRX8mQGAdw=,tag:oxIXIWUyynY+DT81AaFBmQ==,type:str]
sops:
    lastmodified: "2026-08-14T13:44:17Z"
    mac: ENC[AES256_GCM,data:EqlaeDa01FG5p5ZdQmjUC6krpsuN/yCcuXptANjLDvONOPhA1ESuPHFAR6VBpJsaT0Y/WpPwuyYrsqp8Z4L7deZPra5uI+ZD0kwp8MuDg+mrK/TXlkut8GJRTgL5a1ke++M3dpypKhO/T/SHyMPXS2jzJipU/W+3p6tptiEcTVQ=,iv:HobPakLyGLXaYsYJqzxBtXp9BZ5dKToWc3/bIorJxaA=,tag:xCu4znmhee2dKpKXNxjaLA==,type:str]
    pgp:
        - created_at: "2026-08-14T09:57:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ//U8V3zOtezE7PMAatA0AYqgS+Sq5/ZDXfAaQghADOO1YZ
            6VeIIVoGQiOvUnWYgIu7Ebc/zJETUW1uOMQZ8eG8kJ/qrGoIFhM2NEIr302tc7Ro
            zuaL8wmKHgpREmcW7S79ytq0/TTXa87sC1s/Sqm2HmOQPerfF5WCyPAylDMSXfA7
            3vGNpJg4E+KIFH8UFAZ+WeZFJWLg98hrATeUW23bjha8YKlCXAPxeaH3ObdLFVXT
            jqswjPYJuKBaCVzTfLvzYg6pYRM/4W+ILt4u8TLFhzmnxIixwVHEfQ4HwOi50ld3
            X+1xVmAWbY1AWNKSe2y1txyGhV/Y/khuBLwg1rzRHQLdpaeztcZ4oEHvMjwg80cK
            9GCR5EDul/9t0lID9mWERf093RCENSIDKykTf62E4l9DL+3cdK/YViADWjr+aSAN
            6qERgUCSvOYDDpZRovQNjuaNWUXBhZEtWLrvc2IHFpTsimo+nR+TpB5MevxaBHWc
            3DDmpucoW355GPx3Qjb+f8hcLahtbg9VnnBm+QDeBtsyPMqU5mu0RofEs0MxF4qa
            QlvbPRF2uMyXG21ESYuAn6ncKg2qysn0Hvy1Q3ySW8BzM6ob/rLEeRaSTmNgtpsf
            xv5/FNP70Zv8cpi28CRu4beF6GWJyT9Nqq9u9NDfB9yW9iAsa5UlXMBRA80Nr+HS
            XgH/fnJhcU0a5hgiNffkFjAhgcQDVLQIcxO7HsGfZ9n3leH8qCuQGgssNqLVdDvP
            9ZaIwaRrhg2gkIDJT6/IG1vrAI4/H3u4JXJJhrDiXW6PPAxeimhSXcqwu1dbruA=
            =mDSj
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
