apiVersion: ENC[AES256_GCM,data:LV4=,iv:343IEBgWDa7lNuwJQn9LEckBiDgme87b5kRK/L5gzGo=,tag:bs8lMkXCzMsy80wG2Rg+Cw==,type:str]
data:
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:7L7fBLsh7mO1cJjliwcYslmPu08wPv4raoCW/UgWAv4=,iv:xwzpQX9SxdRdRs4xm3N81ZIuDWkgWtPot3aqSiwPWuM=,tag:+CwOy9YVHwpdcA066jn0Hg==,type:str]
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:Ci3skhi+bAM=,iv:kRjKT9LDvory5mthr6c+tfuZelJRTWkO93pyAGvc43w=,tag:CHKXnJgnmxUehXs2NEuJTA==,type:str]
    BAZARR_APIKEY: ENC[AES256_GCM,data:WRmWpmGGYtquJdT6HUpOwIPqPPAe/rV/wiIw4nconj1zKLbG3MlIWJLlNAo=,iv:CYcP7yMoWOlGKMt7YibQ5Z5kyWMGZz0vcsjbjbVChxY=,tag:YMquPerG98QUutXFrkiuPA==,type:str]
    BAZARR_URL: ENC[AES256_GCM,data:mCRYsvRqCTAUL8OoErIL+aHv/fOESWxA9JpeRRMhZvz8NHotMj5NlxSLwIA=,iv:lLyY7G9OoUPBjeKGVXubm3RMIC/wsIcoyhrx+eSaT9c=,tag:k3iWRT8xr1g+b6MqcQbphg==,type:str]
    LIDARR_APIKEY: ENC[AES256_GCM,data:ChPxJY23/hL9yaQjXSBYb7CgkcPsr26b0YiVFD0fFKl5UE8VYZW81T3n+5E=,iv:odgPmoDvAsIQBbJcN6aXUKHdtbwOxfAvBusG4vb5bKg=,tag:SG4NNfxuGL5CsvUVoWA1ng==,type:str]
    LIDARR_URL: ENC[AES256_GCM,data:OKXC17Bk+Xa37+AGPsL1j/wbf4r1lLkmJmk4qUX+avyQco9yFD1H5Hha8f8=,iv:OM+qa+WoP9TeIWxsd82YpftTm7VrCSQ1jKbUZSBUxvU=,tag:40KPlp8ZxPCkukh3IlEeAA==,type:str]
    PROWLARR_APIKEY: ENC[AES256_GCM,data:0SF994BPmHugDTx+VyaLexkvpu2tzV/s0/ekqFfBx1o7N7cjlaLeUuc61iM=,iv:J0gZUGoMUM6OD1z2P11C0uWYstDE3v+mf3zJd+DaXFU=,tag:aJt9eIBFB2tzaF2l9AKsQw==,type:str]
    PROWLARR_URL: ENC[AES256_GCM,data:DXNhjJvkW5w7nNDCO3vOx8XPQmZA23OUDncjEkNvIIqBU/KiSz3PBePwCldgHusD,iv:xrNr2VSnCJTx+cKZzmuFGjR4Nc5WTrH0x3fnMoe56qo=,tag:KtpZeOHZZDiuxbj00pXEpA==,type:str]
    RADARR_APIKEY: ENC[AES256_GCM,data:HHFvNRWnk74iiU6AdtqI+0tSkbpV8SwR5Szc+fPRfTfAZehILonGRBnuQRg=,iv:SVYLec2VjuTI57IP96hj9EeuGvStaxU2RSkQpcI0SlA=,tag:zonmJzT3b5/hkzHI8Y9fgQ==,type:str]
    RADARR_URL: ENC[AES256_GCM,data:0hxd3/knX/cakLtu+mutqcXbHFENKFu9WsAceSaiSiprU36roE4l3HhfZBA=,iv:8Qz6HSJ9aywIeu9/ImIsc4czMQGH/wZVpP/N1ZnXD10=,tag:bj5BGyJxv1DKFxZm6Ff/Fw==,type:str]
    READARR_APIKEY: ENC[AES256_GCM,data:8701Ke/tiUSc58Gru0300g6fYzZH63JIf+sPsPiYIqwt6Ad9pniGFSWhSXI=,iv:tk3N5rRD16/EmJOFLCpXIzlD4+Jrj8GyVEHsk8ZKXf8=,tag:GOqJg5WfvlsZeBFwCaBBAg==,type:str]
    READARR_URL: ENC[AES256_GCM,data:pE6FYzlKYs6xsJhvogH/A4Z2mTOvnmI+BMzyDXvaoT/sH5738hYJRfjqAm0=,iv:L050MSZ3g6JRjD5gUiI/Fd2+nLoytHFuO+4vvb5eZ38=,tag:tkcR256f1mmZYPTeJn45ow==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:iaMYWsXL9m0f17KIsjNnNXmzBDXbVUM3OzOo0RvQeDvinHe7Z6Qh2hRywLk=,iv:vF0/5pmeJNXeBmuWZpVa1RKeVVVtYbV2mX1bXZH+iwk=,tag:T19t18QMkxDSHXptqVQkBw==,type:str]
    SONARR_URL: ENC[AES256_GCM,data:5l4Xrh68JQlRtCW+O+vPKYtvmX9q3R91YbyAc0FHUs/1xgT26GPNxfVSN+8=,iv:RQEjCgKOJpy6queMkvbEjf7PTBwQnnxksmdKUjhRHvg=,tag:3SeUmQfPzuLV/GShEAU0NQ==,type:str]
kind: ENC[AES256_GCM,data:lmmBL86M,iv:pniIMdnvdV8iJZcGRge91brLanto0c+/KOL9qw7Ztc8=,tag:GC6yfJAMJSm2bStTlJYm7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kYIRo9izYtp6ASPvmPA=,iv:9OcYBDjo8yKCET0exMoxuQb6NWJFTOoFrfkW1gqT9p0=,tag:DaV19TUFCjd50qgbxmdLVQ==,type:str]
    namespace: ENC[AES256_GCM,data:EN84XXQ=,iv:sD4P8RjHMoufjTy5whfspUeRWhbJ3mREPl0fu/xre0g=,tag:pOhvANKzNbfGtWA1/jHxew==,type:str]
type: ENC[AES256_GCM,data:8T6Pv9i+,iv:qICz1t0K04K/HfDWd0E4Zv7wmvCqMtlvHUEND0U7Gsk=,tag:UH+nog22d5Y1y5VHBjS7Mg==,type:str]
sops:
    lastmodified: "2026-02-18T13:11:30Z"
    mac: ENC[AES256_GCM,data:QWlXtdXydYd3CnHQ1v8xqWQfds7Fq8PKiSPDdfi+x6L06L8PWQvq2VtJPB+dBzECb7o4+dpYUVMfsWTVXPAI124krGhHXxkcDbLYlqrBoFHg4qm0eH0RDKAFykb/vOXAa336urJh6EBFyBZXWfCQp6UR7fa8plZyTkxu6881NvY=,iv:HFzyEDfEieXns2wypISFtXMIss0VYqifIe4l4/to3zM=,tag:MIiyJSR9jjPTudH5cja9/Q==,type:str]
    pgp:
        - created_at: "2022-09-12T13:41:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA4APDMemWJ+LARAA5iXpfvHHt1NhurYTCtwVWq7fHeZ+f9oPvVzi8kqXpS7L
            FxPA4LeMq4EWAfZvLbDxng2bMGEgSsYJtQH2Pfbsrd0Q5cLexJ2p71HqpthYqVkX
            52qO6meyP2EchyAlu9FUnEsZGqFxDHqPztjPc/5rls6HpuAjpc2nE/fvED9ZLAUc
            bbr7OI9xhzXinvZqWFs/oq825qyvB59SMz0xtyOcQr/mV2AvGLsILmY4KC9IPYY2
            UVkzCpDtyMDmCMPodd2iMynCQsapyrELruEoc3gLiuSk04LrtY7nzQbikS2+GMN7
            4ZCUmArZbruHhJLjWGvpIzHxaa9xVm54f91Nn3VKk+FLOn1Hh8vboFe8Sq+8/oJG
            CtAk/BJnyuhQwFTWyHCCkiFBaDrhgI43Ny68QXqGZrdVCn9CYiGytxg6xL6SPnfD
            78fC1LlFhPn6HlUw9CiTtXxHjJXcFHEviCcTDXCyYyZVa20+5ynP5lo674QeIdtH
            a8q0txpZZdKJmEvn0w3GMBeJ00xRXqg6+o+BO79ieGA0q3Cadt/Qjh2+wkfsKw71
            lIqkluCuvECgJrSNW8g/DcFJtiXnLIlH/qvOxz7WagdpxP6hZfcRE7f5iVyRo0Uz
            ImmBwpepra4cQ4Zu7xFvRE25eU6Q4qPa87lnbI9tSbkdhPLoWts98sYZkiFbZN3S
            UQHi3vrxQ5wJmeHPH35HO28qvg9CbsaJqyr2WvCu5gVGBC3SAOSrNIp1dW2tPW4X
            aMCbkwJln7bJFhRuY3Fc3hekVRTgCB7scprWU/Xco3DWjg==
            =Ge9I
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
