apiVersion: ENC[AES256_GCM,data:i18=,iv:MKXp6ApuE9Fn0XE1UqjOqQ3vWXN8n0D/lEmvrKU/Hy0=,tag:0fI/5vgnOuu5vRMy1uCG9A==,type:str]
data:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:mHvig8CmgE8=,iv:73lODuKIOUOyImZ7GFGtxq4MIfhJuDR3XErNkaNeJpY=,tag:8DZen0FgW2APerKU0kUebw==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:zjvJjHrYJ8SKUgkKZg87oaIwyo+0Ey4uc38gmnkRtyvknKRSj5DL8GyVGnxaLH74JmxpnMtYrylGUxk7Koeh2+BqpLN15P+n8vlhGoeDS8A36xLsDWj4QD2lyRTshwuHxVeaXzuIlWws3JGvwLSQ7m6dk6SAn2GPyC8mhn9oHu9nT/JXMK4AQpY2Z4zq7hq581/v1tMM9+XaJ6mgYhgHnLWR7/9iMYw2M6DMdVMJAtpn7Q60CxXOCVnVuOSjFb30t3l9fp5IfYNLIi/MsXA00gGblX+y7D2z9uW6A4pIy+EF+KhV0IRYediH+7I4ZBMtIWyJuAqyRE5LUyp79JoM4hb403k9BsOrQ/97EU9WS2iKhWlxxY9c6QCTxtIe2P75/W7PI28dLADUszPhkbAb8J8Ws4hMn3nIZvXTl6tX2uqthfmFawhEioZ5Ung87FzDJ0zVBaJfj383JaI9sXE8WYONLunhQ1hi6ALYjB19iJCBJONuRBJJunh+9AGXSsRxVeggB0D5RaJBVqjFYaZs8UqGWv04hIMhQcIiJ/P396HKk47p/FV752iycpX9Tb9NHB8ASg4zLxHnZX3N4fgO3OM+jroRrj+LXqIzUW1APZKLYdwRq6FXTEPnmyJ49FrrpOX5Tq3BpZdv/jhs6nnTY5hef+s5XJpPYrVotjII3fk6Nx/2QdvsWNfBlwSQJDdY7XJJ5jxlE9quxPsdReK61B8aLu51OBaT6QUtfr46aeljahxKlXu3K+dxqcOTuIIxifBQEoQcQ8IKkldhxn/o/Kjdr6rswRf/UZRsn+bRTt8s0Tc/pYfj0CtyzacLJBHc/8Y2f2KdcNcVPM3/PAgQWjXEzspiBrUbEhIgm83GdPGtJaZEuE2zm5zcAK+FLY6+30HYBJuE48Xs93VASWKRa42Oxp2pJgsIKxnjue8dt7MCxHC+nwsbHqQBQFVMImU2Niruz9FywM4W+cZj8qPEZfc/fjKl5yIx4WUqZYguELlti4R7BEQCZbkzxf/5FTRQM+M+piZb3p/vNn7w7rHPBl08GDYcDgjxzCiWdgiSuHMhIomTF6D90L5eep0gYKRpqLtGRDQ+zZa7+HHklY7+Dza9EIc=,iv:Jr03+DZ6b22LzalL/ONIvAgG1Alf1qEiYmP5/yxykbY=,tag:1Ek98QbUqNLTu5VTI6mdCw==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:i9RU96ldQso=,iv:IO/NF6P6CmY6jmKJVqCpmFdvaLG4MgdjxeKkS6xxHpg=,tag:cQMkCbRgLyOMzMYgopgDXg==,type:str]
    RENOVATE_REPOSITORIES: ENC[AES256_GCM,data:vZ5s/Nx8JXqNMVZ141amTp+dTW/YgrL7,iv:yhk/WqhB918sE/+47nuUIH0TIF7tMLSagJsekUpWtv0=,tag:nxvYXT6uXRIg+fqh1dmghg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:dFQ6xNAbf1B1ohlptyRp0PHFMa9CnhUFX63RiAGzkHBdrJOTwXjQLqD5kGN/c2DjJWTSk87LCvM=,iv:L1w/tTxGXuvq5j3IbBy4kvuR7byqRZ6SgJ663+GeUOA=,tag:LizUth9AeqBT8N2MCeCr1Q==,type:str]
kind: ENC[AES256_GCM,data:RlTHZBh9,iv:Gz3yfZLNHhpRAEoY8acDVnZXRNpMYukCYgOhUEBryuE=,tag:c25lAXlULvuDMSVLJCoRfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HF8wvgqAgqM/gu9+,iv:qhJy0VHjg4cerZzrMHOvzoPXWUKF5pj2Wp9GYLLIZNo=,tag:0RURY7BveoJ+6vnT9SD1MQ==,type:str]
    namespace: ENC[AES256_GCM,data:UC0aa76YUFo=,iv:pRzmddITFT8Wb7ht5JyAdT4omTkbXcBPcajktTxepQQ=,tag:vxd0fGFxUoO/rJNkoReS9g==,type:str]
type: ENC[AES256_GCM,data:GUkO4dmw,iv:TuVG5U5wOvnKjepFIfuFYd80fq8FKnKbHv0Fg/+ZgSI=,tag:RlMZZlZJcEcC3Rd+3B54Tw==,type:str]
sops:
    lastmodified: "2026-04-05T09:26:35Z"
    mac: ENC[AES256_GCM,data:6L4xv8T89Fdwnge//z61v9PGgivROLDMIBBfkJ5oo8mQvHWKwwWZHepl8LW5qRi+PdcHkDJ21ycFkJ6YqrqQx6Z3bwgrqQ3gAmfWFB5Jazuqtxc3R4ZjJgHEkhny95pIJy9hVnkwBhG4kUzQsn1gJ0wOvt70dLA9drw7JBFnzG0=,iv:1IT7SlY1M50HCIm7zikqxMMLaxeNR6oiBmRiMe3LBrU=,tag:SZsANz2Px8Ccf8aVwh8i1g==,type:str]
    pgp:
        - created_at: "2026-04-05T09:26:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAAgWcY32qNrsNMhonwPYU3EgQEugaan5up5rfcR1XIluoF
            Qdyq2wx+dYJ39fylvBj6jy1UzJo3dYr8zejxBfs+2ROi0uywnEzwr8H7HluNYStS
            ceH59rSV5DRiyPfbxII89alwhtKKn1/7jioVH8VoiAadFsz9KbLNLnLSdhYCuOrm
            HXGO1e1pA7R85SdDnYdcxneTbi1IcOTNpWloexuWgbdjrNiNb0qos6itn5l7Ie8+
            LO7imQC0YtGGvN6eZs6tqzC7wz6si0bM2RxIWVy8yJWimBXx11J8zo7evJzzhUaj
            T+tg3171bkbtYoZP5SdkX0HAOnHFvgn5L55ND7PmA0JzQtBD2gPLojrCMoo/z9dn
            qm9pIwpebo4AcG+C4bVoqgCi4CnqnjbyVF2H36FgEodTmgtEaPE5ImUR2PlhM+M/
            Y4Kc6F72th98sppkS9/ueLFEEAcT0PPeSJM04Cj/gjEswJ3tQyWzlMP6i45qw+BM
            ZrxubFu4m7St7cwMYacCUkr6Vy4DjeWg7eB9W3obq0jENw05vguKBAv/idOfQleq
            Gld9TM11Yz5mDIttj2qfGgf8iCf87o8T/yOmmW/14IoK3HaarpZAETRqqvR9gSrJ
            jTzrlANU6w2SyGXk62PTwKSvzW+G122z11vQ/8VYKraYoMQ1ESOb7IpZIj6FBm3S
            XAH9iZElDRF+0UiLsvsWYeUG9oucVok+S2tDRhPtK6pz4dsRfM8QyFnnCMMv3HO0
            sLpLt5cSccnHxhMq8kM3lc8g/DYYWuB+a5F9VpbP1bIZEJ7Bl6KhyE6ljhGl
            =5Ju3
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.12.2
