apiVersion: ENC[AES256_GCM,data:evw=,iv:qj3IZMi7/VxTek0bKzdvO6u4IFO8XVQvRN6SCb7WCX4=,tag:yUPjMW+dAbl2jFcEE+HRuQ==,type:str]
kind: ENC[AES256_GCM,data:ql+ws8s/,iv:d4bV1uYnbqzI8voAG8KCnJnkWQY+71RQeHobHZ3sdCU=,tag:ExwGYtIPOonTmGfbn2lbnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PYMNBgLTU6HyTiUW,iv:Au1LVOArWEv3y1An8byrr7Lawd/tRy8aZP7m84xD/Ko=,tag:LErLp3qcHOLramtOLUY5BQ==,type:str]
    namespace: ENC[AES256_GCM,data:Xyt/XQ+pmU4=,iv:S5gOAwewByDXX7tVuLf2jOoTzI4oeVTzZtpbta0fVoY=,tag:nYkun/avclOGqjt5CKTxbQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:4sLwLbIJrbA=,iv:XC2RVY3x3tM3z9HdFWBgDUkVhGv5KGLOrDg4lBQ04i4=,tag:tjFY3HiBphhuG4ySgHA3Ow==,type:str]
type: ENC[AES256_GCM,data:juesD8JV,iv:980blhjasSYT7SeG0UvS0eQ08f7vbBOzzRz939O0DjY=,tag:ss30Yl2rWs4Bu8TYSLoaDQ==,type:str]
stringData:
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:Etd2T9A=,iv:7g4t8ST1t4eMVwN87sL/0KOyBbLdEVrC+LdOQ9F02HE=,tag:4zM6k6m2LwT12xhRZDMvSw==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:ZsmX48Jr,iv:U5pisWC6vunojHdhfmxCUtlSoNfH8cBnNa+fLQsET5M=,tag:QJsbm6T13r0Sc1iB9qRYTA==,type:str]
    RENOVATE_REPOSITORIES: ENC[AES256_GCM,data:jX/r9cgFOIkxfTACTB4Q7IU=,iv:kiYCGJ90WZ0jnt6p2hKa/OBufPYG2/hDdLLkIv3yUa0=,tag:SA4IDXx+XBPCtxUWyPLlVg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:b/k9hKNU2wuip0IVwP5gBLlxr5AaqBEmWB/wYdjRScx0a49YaqHnlA==,iv:faDYuD4oxbk7P40/X2bo+CMFhs+6eSHgWmezUMHNw1w=,tag:qwtxvTmo+ubWVCFqK3exxQ==,type:str]
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:Ux68LqCZ4Z028avsN6NDLqAIW35HXPNfPnGBf6ArYjv32DyjpTq70Fq7tMcHkpxHFEo0VW7hM8wfPrcW8GzVyo9qdNP705YAeiYFoGY3LfatgwT/8ZT7fzkCLgwRxSCk1EcQF6AfTmg7hvOiH3ETKL6e+9xaekjQCQtMCV3+fhgYch0ZhZ6L5A+6IQsvgGXmCEHGyl+agkgS4oOueyaiOYHj3pNYtDmajYV4dH8isYPETcuHlb+7D+/669KQP+3ZgNiihqL8AcrZc5kXRTVH7VzwXLovYhP3nj+WYQhlSVJR14DEMX4rFs7xNFmm2KaN4JL45yqw8InmqoLUBgrONASSPPdRsy3ym57VLSpEku8LTu3vn+lHm41pMwIsBtPT8yGfpht0p71sNFC4DhO4BXZ06bTdBbYw5LYzygSzJ8p6McXhr6ISsSHuhKaBbl5+R5cSxEDYl57rAL6k8U8fDhs9OVHpoiJjHOmixPv86WQ52C9JaquslcL9tDup5Yv+XaszfGZxNmk9Sw7iQyi4hLiHtZAIT8c3LtIwi1PrOligY28cUPyaXZEsKcFe9/8ZrThkU6RsVnDwBSliuZetDY7x9aPcM1KPcvr1Ms+I4PSihqdhdjDbNgx756pxKgD0ndyCEEhQEx+5wet0FDi63X4vCE5dixJAjPGuVCdmofpc4BfCt113hdJS3707HkFhNdUd,iv:A3DQW9B917/NvijXssldhtWddLpe2mGqVI9ELUG/zKY=,tag:Qn3aX5wCCkSQ3UDlb9YiMA==,type:str]
sops:
    lastmodified: "2026-07-30T10:18:42Z"
    mac: ENC[AES256_GCM,data:5Ih0663vXmVR7IE9IFbabjpAz9o+S8Zso65LaVhbO9XzfvigUad3TPBf0fGqSfSNXZWfFV51xRqub+ftUoKx9rWRqQymAPnL8KVrkcnF+V6OYfu2MKwbPXEdY6NvYkwEg4PxOGtCefC6SAlC7ZhYSyjnbJw/W+lp1KJfg13I7o8=,iv:UnGp9tASxmqMupLL5+OldnL0SK4PZGzhbCSQ7RGidZA=,tag:13DMX6UeHYBQgyco8lUjBg==,type:str]
    pgp:
        - created_at: "2026-07-30T10:18:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LAQ/+JooXt9y2T7RecctckJ7oeKE3oxNgN16CFrq5p3RkDUSx
            fKtJ/Lu3uxxhJlzVnxHdAkXVP5hM7hfzYgNU/EpucAF33BGZzJlJ+VozQhypcU26
            aNAiZmPnR1TeAXZPeDmrVxGqzNZ58IaiMe4UmHCqbJ899pVhT8aSgeR7C3HT6CKP
            rCQKLZWsnsTBMnZLFxXuhEheuALnaKQGIpP8BU75tF5sGvNpen6pysbKETUR9RAG
            zTNfQxZLyxqo8+3gL3HDTq7VHson9/SMEJGAIQlakv+lUmn7CNPncmIiRrkUXiQW
            aYqnKSUj2GjiFcsY7wQvFQbp2dZd3B2gTd3Wa0mXXqKFwoWEY7ULeI5g5vXU7BZ1
            gwsLFCLFlmjYfgMZqP1DygXrLhwYjVnqRR1oUN3K5VovijcIx3kAUlZPlpz8LWRz
            nGtz9YDX9/wHNulTvIRL4hDHm1Jfu5oxQEKu2qOmkbGx/ROzGlwEGWHSVP7zuf1G
            1skVYducYbtYSHlxs7DCcTlSwbVEYWGNj6gJt52sR0PQxGWeX5Y8xcO7+Mg016zo
            /YYoo1q9A0sF1ForzoE+1LRfK9hsZDyqgPYze/1xQC093DmDvPaN6txmQFH6qjba
            gRCnldlRNnIsj5tDSwr0N8xM57sqom1KBIBGlzzfovIB+T3T/btNfvSfJqN3KLXS
            XgGsQOzIR596GfYS+5ji+In3FTqBeHKkeUUdfZbBtDbpAD2DbbwaztCkaSmL88A7
            YAUhaNmkHd7wFr1XOUhLWft274HBpJfwqcwmVFzUkVHfvt7p7lF/M/hcWEOpITM=
            =NTfk
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
