#ENC[AES256_GCM,data:9okiGfvUGiQy3JsE92FS73FpsR7VBPmQw7r/rFCZ1Blbxeup+WAENM0sCtZYLoReiKjHjUJfWaZ4sJHJJpyLOzKYuaogfJoC7kY=,iv:9jB4XPqvDpwpr032Dq/9CvO0gHTCl8+HHlj5hFIvIJ8=,tag:Ruc8t36cGCAEbl6uHqk4ig==,type:comment]
upConfig: ENC[AES256_GCM,data:9ch7WT1HJ3nQSQ5xi2/moDnt1NLB6p7Ux0NZF0KGJC66z2PYhP8jV6Cz9iEjC/OVJj/qNf3asJgvQ/2FJBI8LX+a5hbGCMdFb/LIcgSbP+4WK6NG4jcpsEgzlYYH0t8vI7biehiu0tipMrAKN7rkMC0Uj11gUO3nthJCcvXUvKFrRUyKhqFd7qMx/pXhPUGINkpKcigiG1ahD8Xxwurlh7/DB8CXgJkDmqn/26luH4NkZ0GT9EL0fOgt1NaSjc5d52SwP7OK+3lbtJHZEY6m3393V1+/ROWQwy6zyAoBCwpMax1JmU6Zyksg38HVwpq/tEay3UeVbFJyUI+eSSv5BEtta+/oON74IfqB634wbGx0U9vRBx6A8Ess2M1HPYkp3rcjiuyc3FY9HdoEnSmjX+ScfMeZgEd2T22/GKZy4N6627QZd9jeHR85yVm1k77Whll50DxyPrQjmyNLIxZXdzgTpeDg+DG/8w8iFcJgVCAr4Q/o4Z+ht8S2zdoy/U2ezipv0S8WueW2Jcj2VCnNpPRZ6V8vNIuzV6Lv6D/wsr4BOfbvCIq4FvqkNpJtNeD7T9ZN9SAEA2JpRGu3qZ3pokU6192pRm58MWpfUC+D/7XdsotSve5hqGDXX7ZnLYNxX2D7ENUUgsm1aLTfjTE+YIJWsUtZ5TVxElgSqAi9vyb5iHuWTMx3jYhSS6Zd2wUCzRZlTTGRybj0s/mpWKY0ls3nuSjvelO/dQem9mft8h6AyiZk6D4zUm6eYObQn3fJsNYdmKw/bJPuapOu16Kdm+tdr2WN,iv:eVJCDeOq9+Q7p87AAMjtU7TCzKhCwZ2c7D8su+n4uSA=,tag:b/IPN5E0h8pjiy5aG95qhw==,type:str]
sops:
    lastmodified: "2026-06-22T09:27:20Z"
    mac: ENC[AES256_GCM,data:iDSycLNCGvDUUqO1bbJSvUiv4xI5Yw7v1xcR+vFtjGDQriFTEJ+SxRD16LA1zhCD8Gt8WRsnWsJKkX8QdAxlWd7ioq/jxhySMJieuHPwaG/MYQUAkIzW6YFuWe+adQxmHonYuMIIT04NNzMsZj8Wh1Ux1ntuk2/5+hDRLYVS/s0=,iv:AqwsiNThb9sdn2AAkdKPkd3hwSmzjoSHE602QIKXSUY=,tag:JEBvRijh9rPAnRlUpQ72Vw==,type:str]
    pgp:
        - created_at: "2025-12-11T15:17:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAA7gaHOzOZPe4Ddvk67sGDDWKZAXXP0gfKPbntPs4H48MR
            lYgnRBP/UNYLP5x8VH7/N7KBBtBorILqyb9Frum9jASHRxhlP/OjsZdZtmOB97fA
            oyUD4TGijlw7mEWsu+K5PZrL+al76vrIR9tmITjFxeCWzCM7Rjp7rwJcN/2LzYok
            yWRvbnLgcMvbJ9s5JB3iZpdhRYSEHvMIWrTCBqbwinE/vp49p5N7HLPv/arAZjYz
            NagdnWJ8j47K51Sl9dHROilRHGymQADG9pFgGNtOSeH8xR4ikuVIHpCPhHDnJfEm
            nvIrEzpT7q3nBrWDzIHvG+9/HjDbqxtAP0pdYMRoKZ6g7jJR1ZhHoPbreW7zsY7B
            o1qm34qsVQkMV2WbwMRopL1H/fnKjEO6E/B7o4Lp85eXFNBL0qRil2qZJ5VHx0y0
            wYaHQ7S6OMYE6c7CWO3k4wv8MEqIbBuOoxGWl9J8YCbfQt5TkOi3iFnzeqfLqM5j
            5Jif7QACauRMsmuCbMXRqOT281uNjI/p5lJKik4fTF/DFgRbVleaMYC625j9lGmR
            zH99R0p9vneN5UiMG9GV1nLwShAO2pM0uBUUCENo+VJyy4VQKOzg6TSdrUVk8ilK
            fF43wpeN2MWgMa4p+qJT1TEADRa/nC5GvMd8jKM+ze/0eH84UIb8gRA+StgcEajS
            XgH/4Dxsl1+AsLAfUXCar3EjwPrU/HWO45NtkDzb5o7vrIshedOXXU7Aksn6lmcX
            lgRRY5QNlBrYqLOERGf9ZgrElLTb8bpMsi+dNFI823b1MgpG0hRG+3Q5sRCDgeQ=
            =hOw5
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.13.1
