#!/bin/bash

# Check if longhorn repo is already added
if ! helm repo list | grep -q "longhorn"; then
    echo "Adding longhorn Helm repository..."
    helm repo add longhorn https://charts.longhorn.io
else
    echo "longhorn repository already exists"
fi

# Update helm repositories
helm repo update

helm upgrade \
    --install longhorn \
    -n longhorn-system \
    longhorn/longhorn \
    -f values.yaml \
    --create-namespace \
    --version 1.10.1

kubectl apply -f <(sops -d ../../secrets/longhorn-auth.yaml) -n longhorn-system

