#!/bin/bash
PVERSION="v0.14.2"
VERSION="v0.14.3"

mv metallb.yaml metallb-${PVERSION}.yaml
wget -q "https://raw.githubusercontent.com/metallb/metallb/${VERSION}/config/manifests/metallb-native.yaml" -O metallb.yaml
git add .
