---
apiVersion: v2
name: local-path-provisioner
description: Use HostPath for persistent local storage with Kubernetes
type: application
version: 0.0.26
appVersion: "0.0.36"
keywords:
  - storage
  - hostpath
home: https://github.com/rancher/local-path-provisioner
sources:
  - https://github.com/rancher/local-path-provisioner.git
