#!/bin/bash
set -euo pipefail

NAMESPACE="kube-system"
RELEASE_NAME="local-path-provisioner"

helm upgrade --install "${RELEASE_NAME}" . \
  --namespace "${NAMESPACE}" \
  --create-namespace \
  --values values.yaml
