kanboard:
    debug: ENC[AES256_GCM,data:7YXlk20=,iv:MgsZNfYYxIarwHF23TfZWXmp8HoRwtF8/nAWta/3QhE=,tag:T3mCNa3RrjicAxaMus+bkA==,type:bool]
    databaseUrl: ENC[AES256_GCM,data:bAiil2lo/LDvV/DFwJUkmBaUJQKFhwechQrudzeHdiVds1HW5Se+5MS1Mg3gjCGyzkxOppmr7NUIKSmEOvvODpJoTIKKnPqIVs5BZrFJ+fQDbWRXZOQ=,iv:6XsvhGhStocbQ7COgQOY6tNJzxsOZ12AHxk01QykOe0=,tag:dE6ig0IBz08ZhE7KqzvoPQ==,type:str]
    #ENC[AES256_GCM,data:luGuTBVdpa/wlU0MrIpGHkEEEz6ZLW8ZTrwup8AfJBwPtaaDlA==,iv:I38WCIe2idB4cwlNH1+jbvZXjttnoSHCxiuIkq7Rhv4=,tag:SUqLzy6OisF/yT1/GRNvGw==,type:comment]
    plugin_installer: ENC[AES256_GCM,data:DeuFTQ==,iv:3oz7XPO7vw4r9WbB4Gj+68JF9TzngpjQboJNYLJfGGs=,tag:WK9msYgEEjM7ocK1fKj3+g==,type:bool]
    #ENC[AES256_GCM,data:GvRlFhEIFIMIGyFhxeze9pdDNgtOLJRv9mOmWNtZpvIs2fGBtqat7lItMYFCVbWLFawevm9j1pZYFtuYdg==,iv:bYk73LsesYWB+pwfD2ny1prp8G+q0Djat+7tlPvzp/A=,tag:3WHSOHF3/PhcS2KlWyieUw==,type:comment]
    #ENC[AES256_GCM,data:PRbs4e6EERO9YUc9QYHbPq5bn4VW7iLdHYBRPuw=,iv:HUI4oscSKrYRp1D38wh3j21vQGrxMKNXUjvPTXysuX4=,tag:/kz+yeXxUBmiMecHs3lF1g==,type:comment]
sops:
    lastmodified: "2026-07-31T09:06:26Z"
    mac: ENC[AES256_GCM,data:styrPzvAhEoDnr2gIK54djxbXi8dSSA9OfPmmZXXGwY+zqVOXoQ94j4baujQpC2O6iZ3277+Ii5biXZ17H3g6iGZp0YB9GQW9RFlEMbvD72f9CXiSjQwn9JQZGWSofBfHuobqKO9Uoy9LBAvIMhnldIHPOF1yK4vd0qURWHtFZ8=,iv:YLiTHHLtqqXhhHt66TLjVm5iIzSRgN889Jtg7dJEZ1M=,tag:43C8/FDpSYUA0vsFdnCxzw==,type:str]
    pgp:
        - created_at: "2026-01-25T18:11:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4APDMemWJ+LARAA2CErMpA8wPq4WwUWCpLaLBTayi2kOFnohrKQEkzMqFQi
            udXcQFI45ngIj0+yZWNvNmL+W3pZ8j1ageWBw5VFx/CIwaPy0LndVtxlKJtlMVfv
            pJ/fdRLR6nW8b80EewKRNxxz387f9lnJgaMd0XCPCzgm7HY4Hx7TL48APdRow1WQ
            BYn59WePyhnLYdZMndfVRF8pT/u/dSURh4Y2hGiirT4ARTAHGqeBeuNzcODB8Ewp
            B155bRCdrFz+z/lFT8dkORCKn1fhFe6TNiHtkG4CE9LJ4ZKt0IlOllE3EZjSdUl5
            YZdu1m4+vX4CGoTfnqLQCNZNYEZnPfXTpfzhiiA0dsZsvyrQKUPkN6eLBYBe6QK1
            WJpS/ZM+uXU4GL2cKkWEm/Cx0eFdoa2PJ6o3mXPNLm6hRlXu3Tk+IsDQ6f27L7Mu
            4W5L4PyHL5b+8dxYwWKak/Jf6/BRIWCxdgWmjx+N3jQcvZV2DX1GLPl9kEpK/rw1
            nptntJk6fpVV+S4sAsMeGUeE8mVV1S8NgCbdQCTYaITR0k99fUHjGhAuSicBheOW
            fjaRhOvbo1busrDu5rZDZk4Cxtp5k5K6aAi/CmO/QyGGt66pyWEpEYYm+s+PQPhk
            +zTqbR4ciqJiXuxrSLrCZ565Z/M9IqPnvuAn5z984SBeHbUkAKuG1TR1lB+wX9fS
            XAE/gdPIOL2wNpXQCi0mNnuSOXzROrRSg/jCzr97F1Zjw4P8p2UI8/+60rV4iLvt
            UM607dwSXqKrEVXL87zZjeDSsfbUK8V4FsbU8s9m+ZEKcCN2Xjhx822+skd0
            =LVLG
            -----END PGP MESSAGE-----
          fp: D6380604E0A09E002380524F0AECB9DCA67CB14C
    unencrypted_suffix: _unencrypted
    version: 3.13.3
