{
 "title": "ElasticSearch",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Documents indexed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Total Indices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_indices_get_total{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Shards Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Unassigned"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Initializing"
    },
    {
     "expr": "sum(elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"})",
     "legendFormat": "Relocating"
    }
   ]
  },
  {
   "title": "Total Scrapes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_total_scrapes)"
    }
   ]
  },
  {
   "title": "Json Parse Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_cluster_health_json_parse_failures[1h]))"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_merges_total{cluster=~\"$cluster\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "elasticsearch_indices_merges_current{cluster=~\"$cluster\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "elasticsearch_indices_merges_docs_total{cluster=~\"$cluster\"}",
     "legendFormat": "Docs"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ name }} {{ gc }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  }
 ]
}