{
 "title": "Health Data Influx",
 "time": { "from": "now-18M", "to": "now" },
 "panels": [
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierStepCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body Mass",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierBodyMass",
     "query": "SELECT (\"value\") FROM \"HKQuantityTypeIdentifierBodyMass\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body Fat %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierBodyFatPercentage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance walked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierDistanceWalkingRunning",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lean Body Mass",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierLeanBodyMass",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active energy burned",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierActiveEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierHeartRate",
     "query": "SELECT (\"value\") FROM \"HKQuantityTypeIdentifierBodyMass\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierHeartRate",
     "query": "SELECT (\"value\") FROM \"HKQuantityTypeIdentifierBodyMass\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierHeartRate",
     "query": "SELECT (\"value\") FROM \"HKQuantityTypeIdentifierBodyMass\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Basal energy burned",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierBasalEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blood Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierBloodPressureSystolic",
     "query": "SELECT (\"value\") FROM \"HKQuantityTypeIdentifierBodyMass\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HKQuantityTypeIdentifierBloodPressureDiastolic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}