{
 "title": "Kubernetes Cluster (Prometheus)",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes) - sum (node_filesystem_free_bytes)) / sum (node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) ",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated)"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "StatefulSet Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas)"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Updated",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_updated)"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Unavailable",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_unavailable)"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "grafana-singlestat-panel",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 41 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "grafana-singlestat-panel",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 41 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "grafana-singlestat-panel",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 41 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{namespace!=\"kube-system\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_container_info{namespace!=\"kube-system\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated)"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 69 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 73 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_job_status_succeeded)" }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 73 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_job_status_active)" }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 73 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_job_status_failed)" }
   ]
  }
 ]
}