{
 "title": "Media Stats",
 "tags": [ "media" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_system_status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total[7d]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "{app=\"radarr\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_monitored_total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "radarr_movie_wanted_total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total[30d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale", "label": "movies by quality" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sonarr_system_status" }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_total" }
   ]
  },
  {
   "title": "Seasones",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_season_total" }
   ]
  },
  {
   "title": "d/l month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(sonarr_episode_downloaded_total[30d]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"sonarr\"}"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_total" }
   ]
  },
  {
   "title": "Missing EP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total" }
   ]
  },
  {
   "title": "d/l past week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total[7d]))"
    }
   ]
  }
 ]
}