{
 "title": "Pi k3s Simple Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total CPU Cores",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"kubernetes-pods\"})"
    }
   ]
  },
  {
   "title": "Node Load 5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load5{job=\"kubernetes-pods\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~'ext4|xfs',job=\"kubernetes-pods\"}",
     "legendFormat": "{{instance}} | {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_network_up{device='eth0',job=\"kubernetes-pods\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"kubernetes-pods\",sensor=\"temp0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_duration_seconds_sum[5m]))"
    }
   ]
  },
  {
   "title": "TCP Established Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"kubernetes-pods\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmit Rate (In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"kubernetes-pods\"}[5m]))",
     "legendFormat": "IN"
    },
    {
     "expr": "-sum(rate(node_network_transmit_bytes_total{job=\"kubernetes-pods\"}[5m]))",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}