{
 "title": "VPA Recommendations",
 "description": "Hari ONLY Vertical Pod Autoscalar Recommendations vs. Utilization vs. Requests & Limits",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "recommendation",
    "label": "Recommendation",
    "query": "target,uncappedtarget,lowerbound,upperbound"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels, job)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels{job=~'.*'}, namespace)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(kube_verticalpodautoscaler_labels{job=~'.*', namespace='$namespace'}, target_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory $recommendation vs Memory Usage",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='$namespace', pod=~'$targetName(.+)', container!='', container!='POD'}) by (container, pod)",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "avg(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource='memory', namespace='$namespace', target_name='$targetName'}) by (container)",
     "legendFormat": "{{container}} recommendation"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations vs Requests and Limits",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{namespace='$namespace', target_name='$targetName', resource='memory'}) by (container)",
     "legendFormat": "{{container}} recommendation"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource='memory', namespace='$namespace', pod=~'$targetName(.+)'}) by (container)",
     "legendFormat": "$targetName-{{container}} requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource='memory', namespace='$namespace', pod=~'$targetName(.+)'}) by (container)",
     "legendFormat": "$targetName-{{container}} limits"
    }
   ]
  },
  {
   "title": "CPU $recommendation vs CPU Usage",
   "type": "timeseries",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='$namespace', pod=~'$targetName-(.+)', container!='', container!='POD'}[15m])) by (container,pod) * 1000",
     "legendFormat": "{{pod}}-{{container}} actual usage"
    },
    {
     "expr": "avg(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource='cpu', namespace='$namespace', target_name='$targetName'}) by (container) * 1000",
     "legendFormat": "{{container}} recommendation"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations vs Requests and Limits",
   "type": "timeseries",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{namespace='$namespace', target_name='$targetName', resource='cpu'}) by (container) * 1000",
     "legendFormat": "{{container}} recommendation"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource='cpu', namespace='$namespace', pod=~'$targetName(.+)'}) by (container) * 1000",
     "legendFormat": "$targetName-{{container}} requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource='cpu', namespace='$namespace', pod=~'$targetName(.+)'}) by (container) * 1000",
     "legendFormat": "$targetName-{{container}} limits"
    }
   ]
  }
 ]
}