---
apiVersion: v2
name: event-exporter
description: Export Kubernetes events to multiple destinations with routing and filtering
type: application
version: 0.1.1
appVersion: "1.7"
home: https://github.com/resmoio/kubernetes-event-exporter
