#!/bin/bash
PVERSION="v0.13.9"
VERSION="v0.13.10"

mv metallb.yaml metallb-${PVERSION}.yaml
wget -q "https://raw.githubusercontent.com/metallb/metallb/${VERSION}/config/manifests/metallb-native.yaml" -O metallb.yaml
git add .
