#!/bin/bash
set -euo pipefail

kubectl apply -f minio/

velero install \
  --plugins szpaczyn/velero-plugin-for-aws:v1.2.0 \
  --provider aws \
  --bucket velero \
  --secret-file <(sops -d ../../secrets/aws-credentials) \
  --use-volume-snapshots=false \
  --velero-pod-cpu-limit=1000m \
  --velero-pod-cpu-request=200m \
  --velero-pod-mem-limit=128Mi \
  --velero-pod-mem-request=32Mi \
  --use-restic \
  --restic-pod-cpu-request=200m \
  --restic-pod-cpu-limit=200m \
  --restic-pod-mem-request=32Mi \
  --restic-pod-mem-limit=128Mi \
  --default-volumes-to-restic \
  --backup-location-config \
  region=minio,s3ForcePathStyle=true,s3Url=http://minio.velero.svc:9000

velero create schedule daily --schedule="28 4 * * *" --ttl 2160h0m0s

kubectl apply -f restic-cm.yaml
kubectl apply -f restic-podsecuritypolicy.yaml
