---
- name: Create zsh plugins directory
  ansible.builtin.file:
    path: "/{{ ansible_user }}/.zsh/plugins"
    state: directory
    owner: "{{ ansible_user }}"
    group: root
    mode: "0755"

- name: Zsh config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/{{ ansible_user }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: root
    mode: "0644"
  loop:
    - { src: zshrc.j2, dest: .zshrc }
    - { src: zshenv.j2, dest: .zsh/zshenv }
    - { src: alias.j2, dest: .zsh/alias }

- name: Zsh plugins
  ansible.builtin.copy:
    src: "zsh-plugins/{{ item }}"
    dest: "/{{ ansible_user }}/.zsh/plugins/{{ item }}"
    owner: "{{ ansible_user }}"
    group: root
    mode: "0644"
  loop: "{{ dotfiles_zsh_plugins + dotfiles_zsh_plugins_extra }}"

- name: Create zsh completion directory
  ansible.builtin.file:
    path: "/{{ ansible_user }}/.zsh/plugins/completion"
    state: directory
    owner: "{{ ansible_user }}"
    group: root
    mode: "0755"
  when: "'gentoo' not in group_names"

- name: Zsh completions
  ansible.builtin.copy:
    src: "zsh-plugins/completion/{{ item }}"
    dest: "/{{ ansible_user }}/.zsh/plugins/completion/{{ item }}"
    owner: "{{ ansible_user }}"
    group: root
    mode: "0644"
  loop: "{{ dotfiles_zsh_completions }}"
  when: "'gentoo' not in group_names"
