---
- name: Install zsh-syntax-highlighting package
  ansible.builtin.apt:
    name: zsh-syntax-highlighting
    install_recommends: false
  register: dotfiles_apt_zsh_syntax_highlighting
  retries: 5
  until: dotfiles_apt_zsh_syntax_highlighting is success
  when: "'gentoo' not in group_names"

- name: Zshrc
  ansible.builtin.copy:
    src: "{{ dotfiles_zshrc_src }}"
    dest: "/{{ ansible_user }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: root
    mode: "0644"

- name: Create zsh plugins directory
  ansible.builtin.file:
    path: "/{{ ansible_user }}/.zsh/plugins"
    state: directory
    owner: "{{ ansible_user }}"
    group: root
    mode: "0755"

- name: Zsh plugins
  ansible.builtin.copy:
    src: "zsh-plugins/{{ item }}"
    dest: "/{{ ansible_user }}/.zsh/plugins/{{ item }}"
    owner: "{{ ansible_user }}"
    group: root
    mode: "0644"
  loop: "{{ dotfiles_zsh_plugins }}"
