#!/bin/bash
kubectl apply -f minio/

velero install \
    --plugins registry.shpaq.org/velero-plugin-for-aws:v1.1.0 \
    --provider aws \
    --bucket velero \
    --secret-file ./credentials-minio \
    --use-volume-snapshots=true \
    --use-restic \
    --backup-location-config \
    region=minio,s3ForcePathStyle=true,s3Url=http://minio.velero.svc:9000
#    --dry-run -o yaml > velero.yaml

kubectl apply -f restic-cm.yaml
#kubectl apply -f velero.yaml
