#!/bin/bash
kubectl create ns longhorn-system
sops -d ../../secrets/longhorn-auth.yaml > 00-auth.yaml
kubectl apply -f ./00-auth.yaml
sops -d ../../secrets/longhorn-values.yaml > values.yaml

helm upgrade --install longhorn -n longhorn-system longhorn/longhorn -f values.yaml

rm -rf 00-auth.yaml
rm -rf values.yaml
