---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: apps
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:18.4
            command: ["/bin/sh"]
            args:
              - "-c"
              - |
                echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass
                for DB in grafana bitwarden gitea kanboard nextcloud keycloak whoops; do
                  echo "Backing up ${DB}..."
                  pg_dump -U postgres -h morphine-postgresql "${DB}" | gzip > /var/backups/"${DB}"/"${DB}"-$(date +"%Y%m%d-%H%M").sql.gz
                  if [ $? -eq 0 ]; then
                    echo "  OK: ${DB}"
                  else
                    echo "  FAILED: ${DB}" >&2
                  fi
                done
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-pgpass
                  key: pgpass
            volumeMounts:
            - mountPath: /var/backups
              name: postgres-storage
          restartPolicy: Never
          volumes:
          - name: postgres-storage
            hostPath:
              path: /data/nfs/postgres-backups
              type: DirectoryOrCreate
