#!/bin/bash

# Check if bitnami repo is already added
if ! helm repo list | grep -q "bitnami"; then
    echo "Adding bitnami Helm repository..."
    helm repo add bitnami https://charts.bitnami.com/bitnami
else
    echo "bitnami repository already exists"
fi

# Update helm repositories
#helm repo update

#helm repo add bitnami https://charts.bitnami.com/bitnami

helm upgrade \
    --install morphine \
    bitnami/postgresql \
    --namespace apps \
    --values values-public.yaml \
    --values <(sops -d ../../secrets/postgresql-values.yaml)

kubectl apply -f <(sops -d ../../secrets/postgresql-pgpass.yaml)
kubectl apply -f backup-job.yaml
