#!/bin/bash

# Check if bitnami repo is already added
if ! helm repo list | grep -q "bitnami"; then
    echo "Adding bitnami Helm repository..."
    helm repo add bitnami https://charts.bitnami.com/bitnami
else
    echo "bitnami repository already exists"
fi

# Update helm repositories
helm repo update

#helm repo add bitnami https://charts.bitnami.com/bitnami

sops -d \
    --output  values.yaml \
    ../../secrets/postgresql-values.yaml

sops -d \
    --output pgpass.yaml \
    ../../secrets/postgresql-pgpass.yaml

helm upgrade --install morphine bitnami/postgresql -n apps -f values.yaml

kubectl apply -f pgpass.yaml
kubectl apply -f backup-job.yaml

rm -rf values.yaml pgpass.yaml
