---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gentoo.fullname" . }}
  labels:
    {{- include "gentoo.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "gentoo.fullname" . }}
  selector:
    matchLabels:
      {{- include "gentoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gentoo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "gentoo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: data
              readOnly: false
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
